#include "qcae/task_service.hpp"
#include <cstring>
struct BinaryRead {
 std::string_view source; std::size_t pos{};
 std::uint64_t integer(){demand(source.size()-pos>=8,"u64 framing");std::uint64_t n{};for(unsigned i=0;i<8;++i)n|=std::uint64_t(static_cast<unsigned char>(source[pos++]))<<(8*i);return n;}
 std::string text(){auto n=integer();demand(n<=source.size()-pos,"text framing");auto value=std::string(source.substr(pos,n));pos+=n;return value;}
};
void u64(std::string& out,std::uint64_t n){for(unsigned i=0;i<8;++i)out.push_back(static_cast<char>(n>>(8*i)));}
void text8(std::string& out,std::string_view text){u64(out,text.size());out.append(text);}
std::shared_ptr<const OwnedRowImage> read_image(std::uint64_t space,std::string id,std::string bytes){BinaryRead r{bytes};demand(r.text()=="QCAE-OWNED-ROW"&&r.integer()==1,"owned envelope");auto owner=r.text();auto schema=r.integer();auto payload=r.text();demand(r.pos==bytes.size(),"owned trailing");return std::make_shared<const OwnedRowImage>(OwnedRowImage{{static_cast<StoreSpace>(space),std::move(id)},std::move(owner),static_cast<std::uint32_t>(schema),std::make_shared<const std::string>(std::move(payload)),{}});}
std::string image_bytes(const OwnedRowImage& image){std::string out;text8(out,"QCAE-OWNED-ROW");u64(out,1);text8(out,image.owner);u64(out,image.schema_version);text8(out,*image.payload);return out;}
void rewrite_project(std::string_view from,std::string_view to){
 std::ifstream input(std::string(from),std::ios::binary);demand(input.good(),"project input missing");const std::string old{std::istreambuf_iterator<char>(input),{}};BinaryRead r{old};demand(r.text()=="QCAE-RECORD-PROJECT"&&r.integer()==2,"project header");for(unsigned n=0;n<3;++n)(void)r.text();for(auto n=r.integer();n>0;--n)(void)r.text();const auto prefix=std::string(old.substr(0,r.pos));std::vector<std::shared_ptr<const OwnedRowImage>> rows;for(auto n=r.integer();n>0;--n){auto space=r.integer();auto id=r.text();auto envelope=r.text();rows.push_back(read_image(space,std::move(id),std::move(envelope)));}demand(r.pos==old.size(),"project trailing");
 auto selected=std::find_if(rows.begin(),rows.end(),[](const auto& row){return row->owner=="qcae.solver.result";});demand(selected!=rows.end(),"no original published result");auto stored=d::decode_solver_result_row(**selected);auto& origin=stored.parsed.origin;const auto oldtask=origin.run.request.task_id,oldrun=origin.run.request.run_id,oldresult=stored.artifact.artifact_id;
 auto run_row=std::find_if(rows.begin(),rows.end(),[&](const auto& row){return row->key.identity==oldrun&&row->owner=="qcae.solver.run";});auto task_row=std::find_if(rows.begin(),rows.end(),[&](const auto& row){return row->key.identity==oldtask&&row->owner=="qcae.runtime.task";});demand(run_row!=rows.end()&&task_row!=rows.end(),"missing real run/task");auto current=decode_solver_owned_run(**run_row);auto task=decode_task_record(*(*task_row)->payload);
 origin.run.request.task_id=std::string(121,'\x01');origin.run.request.run_id="run-"+origin.run.request.task_id;origin.run.request.run_directory=std::filesystem::path(origin.run.request.run_directory).parent_path()/origin.run.request.run_id;
 stored.artifact=d::solver_result_artifact(stored.parsed,std::filesystem::path(origin.run.request.run_directory)/".qcae-result");current.run.request=origin.run.request;current.result_artifact=stored.artifact;task.id=origin.run.request.task_id;demand(task.artifact_receipt.has_value(),"original complete receipt");task.artifact_receipt->artifact_id=stored.artifact.artifact_id;task.artifact_receipt->manifest_sha256=artifact_sha256(stored.artifact.manifest);validate_solver_task(current,task);d::validate_solver_result_link(stored.parsed,current);
 const auto profile=NastranCodec{}.definition().reference;std::erase_if(rows,[&](const auto& row){return row->key.identity==oldrun||row->key.identity==oldtask||row->key.identity==oldresult||row->owner==d::solver_validation_owner;});rows.push_back(solver_owned_row(current));rows.push_back(d::solver_result_row(stored));rows.push_back(std::make_shared<const OwnedRowImage>(OwnedRowImage{{StoreSpace::task_record,task.id},"qcae.runtime.task",1,std::make_shared<const std::string>(encode_task_record(task)),{}}));
 d::SolverValidationIndex index{origin.run.request.run_id,origin.principal,{}};for(unsigned n=1;n<=16;++n){auto fact=good(d::prepare_solver_validation(stored,profile));fact.idempotency_key="independent-carried-"+std::to_string(n);fact.ordinal=n;fact.signature=record_wire::strings(std::array<std::string,8>{origin.run.request.input.document.value,origin.run.request.input.epoch.value,std::to_string(origin.run.request.input.revision),fact.run_id,fact.principal,profile.profile_id,profile.profile_version,profile.definition_digest});auto image=d::solver_validation_row(fact);d::validate_solver_validation_link(d::decode_solver_validation_row(*image),stored,profile);index.report_rows.push_back(image->key.identity);rows.push_back(image);}rows.push_back(d::solver_validation_index_row(index));
 std::sort(rows.begin(),rows.end(),[](const auto& a,const auto& b){return a->key<b->key;});std::string output=prefix;u64(output,rows.size());for(const auto& row:rows){u64(output,static_cast<std::uint64_t>(row->key.space));text8(output,row->key.identity);text8(output,image_bytes(*row));}std::ofstream file(std::string(to),std::ios::binary);file.write(output.data(),output.size());demand(file.good(),"private project write");std::cout<<"carried_project_crosslink=true synthetic=true real_solver=false task_control_bytes=121 reports=16 bytes="<<output.size()<<'\n';
}
