// Generated by tools/generate_operation_contracts.py; edit schemas/operations instead.
#pragma once
#include "qcae/operation_registry.hpp"

namespace qcae::operations {
inline constexpr std::string_view operation_schema_digest = "4e26391a6f0568767d647bd3b946b604dbfff5d3b7146b21df4742f1c9039afc";

struct AnalysisCheckInput {
    EntityId analysis_id{};
};

template <> struct InputTraits<AnalysisCheckInput> {
    static constexpr std::string_view operation_id = "analysis.check";
    static constexpr std::string_view schema_id = "qcae.operation.analysis.check.v1";
    static OperationDefinition definition() {
        return {"analysis.check", 1, "qcae.operation.analysis.check.v1",
                OperationEffect::auxiliary_write,
                {true, true, true, true, false},
                {
                    {1, "analysis_id", "entity_id", {}, true, false}
                }};
    }

    static Result<AnalysisCheckInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 1> allowed{"analysis_id"};
        static constexpr std::array<std::string_view, 1> required{"analysis_id"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto analysis_id = wire::entity_id(fields.at("analysis_id"), "input.analysis_id");
        if (!analysis_id.ok()) {
            return {analysis_id.status, std::nullopt, analysis_id.error};
        }
        AnalysisCheckInput input{*analysis_id.value};
        wire::observe_input_copy(input, input.analysis_id);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const AnalysisCheckInput& input) {
        Value::Object object;
        object.emplace("analysis_id", Value(input.analysis_id.value));
        wire::observe_key("analysis_id");
        return Value(std::move(object));
    }
};

struct AnalysisCreateInput {
    std::string name{};
    std::vector<EntityId> load_case_ids{};
};

template <> struct InputTraits<AnalysisCreateInput> {
    static constexpr std::string_view operation_id = "analysis.create";
    static constexpr std::string_view schema_id = "qcae.operation.analysis.create.v1";
    static OperationDefinition definition() {
        return {"analysis.create", 1, "qcae.operation.analysis.create.v1",
                OperationEffect::document_write,
                {true, true, true, true, true},
                {
                    {1, "name", "string", {}, true, false},
                    {2, "load_case_ids", "entity_id_array", {}, true, true}
                }};
    }

    static Result<AnalysisCreateInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 2> allowed{"name", "load_case_ids"};
        static constexpr std::array<std::string_view, 2> required{"name", "load_case_ids"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto name = wire::string_value(fields.at("name"), "input.name");
        if (!name.ok()) {
            return {name.status, std::nullopt, name.error};
        }
        const auto load_case_ids = wire::entity_id_array(fields.at("load_case_ids"), "input.load_case_ids", true);
        if (!load_case_ids.ok()) {
            return {load_case_ids.status, std::nullopt, load_case_ids.error};
        }
        AnalysisCreateInput input{*name.value, *load_case_ids.value};
        wire::observe_input_copy(input, input.name, input.load_case_ids);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const AnalysisCreateInput& input) {
        Value::Object object;
        object.emplace("name", Value(input.name));
        wire::observe_key("name");
        object.emplace("load_case_ids", wire::to_value(input.load_case_ids));
        wire::observe_key("load_case_ids");
        return Value(std::move(object));
    }
};

struct AnalysisGetIssuesInput {
    std::string check_id{};
};

template <> struct InputTraits<AnalysisGetIssuesInput> {
    static constexpr std::string_view operation_id = "analysis.get_issues";
    static constexpr std::string_view schema_id = "qcae.operation.analysis.get_issues.v1";
    static OperationDefinition definition() {
        return {"analysis.get_issues", 1, "qcae.operation.analysis.get_issues.v1",
                OperationEffect::read_only,
                {true, true, false, false, false},
                {
                    {1, "check_id", "string", {}, true, false}
                }};
    }

    static Result<AnalysisGetIssuesInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 1> allowed{"check_id"};
        static constexpr std::array<std::string_view, 1> required{"check_id"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto check_id = wire::string_value(fields.at("check_id"), "input.check_id");
        if (!check_id.ok()) {
            return {check_id.status, std::nullopt, check_id.error};
        }
        AnalysisGetIssuesInput input{*check_id.value};
        wire::observe_input_copy(input, input.check_id);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const AnalysisGetIssuesInput& input) {
        Value::Object object;
        object.emplace("check_id", Value(input.check_id));
        wire::observe_key("check_id");
        return Value(std::move(object));
    }
};

struct AnalysisGetResultInput {
    std::string run_id{};
};

template <> struct InputTraits<AnalysisGetResultInput> {
    static constexpr std::string_view operation_id = "analysis.get_result";
    static constexpr std::string_view schema_id = "qcae.operation.analysis.get_result.v1";
    static OperationDefinition definition() {
        return {"analysis.get_result", 1, "qcae.operation.analysis.get_result.v1",
                OperationEffect::read_only,
                {true, true, false, false, false},
                {
                    {1, "run_id", "string", {}, true, false}
                }};
    }

    static Result<AnalysisGetResultInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 1> allowed{"run_id"};
        static constexpr std::array<std::string_view, 1> required{"run_id"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto run_id = wire::string_value(fields.at("run_id"), "input.run_id");
        if (!run_id.ok()) {
            return {run_id.status, std::nullopt, run_id.error};
        }
        AnalysisGetResultInput input{*run_id.value};
        wire::observe_input_copy(input, input.run_id);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const AnalysisGetResultInput& input) {
        Value::Object object;
        object.emplace("run_id", Value(input.run_id));
        wire::observe_key("run_id");
        return Value(std::move(object));
    }
};

struct AnalysisGetRunInput {
    std::string run_id{};
};

template <> struct InputTraits<AnalysisGetRunInput> {
    static constexpr std::string_view operation_id = "analysis.get_run";
    static constexpr std::string_view schema_id = "qcae.operation.analysis.get_run.v1";
    static OperationDefinition definition() {
        return {"analysis.get_run", 1, "qcae.operation.analysis.get_run.v1",
                OperationEffect::read_only,
                {true, true, false, false, false},
                {
                    {1, "run_id", "string", {}, true, false}
                }};
    }

    static Result<AnalysisGetRunInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 1> allowed{"run_id"};
        static constexpr std::array<std::string_view, 1> required{"run_id"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto run_id = wire::string_value(fields.at("run_id"), "input.run_id");
        if (!run_id.ok()) {
            return {run_id.status, std::nullopt, run_id.error};
        }
        AnalysisGetRunInput input{*run_id.value};
        wire::observe_input_copy(input, input.run_id);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const AnalysisGetRunInput& input) {
        Value::Object object;
        object.emplace("run_id", Value(input.run_id));
        wire::observe_key("run_id");
        return Value(std::move(object));
    }
};

struct AnalysisReconcileResultInput {
    std::string run_id{};
};

template <> struct InputTraits<AnalysisReconcileResultInput> {
    static constexpr std::string_view operation_id = "analysis.reconcile_result";
    static constexpr std::string_view schema_id = "qcae.operation.analysis.reconcile_result.v1";
    static OperationDefinition definition() {
        return {"analysis.reconcile_result", 1, "qcae.operation.analysis.reconcile_result.v1",
                OperationEffect::auxiliary_write,
                {true, true, true, true, false},
                {
                    {1, "run_id", "string", {}, true, false}
                }};
    }

    static Result<AnalysisReconcileResultInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 1> allowed{"run_id"};
        static constexpr std::array<std::string_view, 1> required{"run_id"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto run_id = wire::string_value(fields.at("run_id"), "input.run_id");
        if (!run_id.ok()) {
            return {run_id.status, std::nullopt, run_id.error};
        }
        AnalysisReconcileResultInput input{*run_id.value};
        wire::observe_input_copy(input, input.run_id);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const AnalysisReconcileResultInput& input) {
        Value::Object object;
        object.emplace("run_id", Value(input.run_id));
        wire::observe_key("run_id");
        return Value(std::move(object));
    }
};

struct AnalysisStartInput {
    EntityId analysis_id{};
    std::string artifact_id{};
    std::string run_config_id{};
};

template <> struct InputTraits<AnalysisStartInput> {
    static constexpr std::string_view operation_id = "analysis.start";
    static constexpr std::string_view schema_id = "qcae.operation.analysis.start.v1";
    static OperationDefinition definition() {
        return {"analysis.start", 1, "qcae.operation.analysis.start.v1",
                OperationEffect::background_task,
                {true, true, true, true, true},
                {
                    {1, "analysis_id", "entity_id", {}, true, false},
                    {2, "artifact_id", "string", {}, true, false},
                    {3, "run_config_id", "string", {}, true, false}
                }};
    }

    static Result<AnalysisStartInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 3> allowed{"analysis_id", "artifact_id", "run_config_id"};
        static constexpr std::array<std::string_view, 3> required{"analysis_id", "artifact_id", "run_config_id"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto analysis_id = wire::entity_id(fields.at("analysis_id"), "input.analysis_id");
        if (!analysis_id.ok()) {
            return {analysis_id.status, std::nullopt, analysis_id.error};
        }
        const auto artifact_id = wire::string_value(fields.at("artifact_id"), "input.artifact_id");
        if (!artifact_id.ok()) {
            return {artifact_id.status, std::nullopt, artifact_id.error};
        }
        const auto run_config_id = wire::string_value(fields.at("run_config_id"), "input.run_config_id");
        if (!run_config_id.ok()) {
            return {run_config_id.status, std::nullopt, run_config_id.error};
        }
        AnalysisStartInput input{*analysis_id.value, *artifact_id.value, *run_config_id.value};
        wire::observe_input_copy(input, input.analysis_id, input.artifact_id, input.run_config_id);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const AnalysisStartInput& input) {
        Value::Object object;
        object.emplace("analysis_id", Value(input.analysis_id.value));
        wire::observe_key("analysis_id");
        object.emplace("artifact_id", Value(input.artifact_id));
        wire::observe_key("artifact_id");
        object.emplace("run_config_id", Value(input.run_config_id));
        wire::observe_key("run_config_id");
        return Value(std::move(object));
    }
};

struct AnalysisValidateResultInput {
    std::string run_id{};
};

template <> struct InputTraits<AnalysisValidateResultInput> {
    static constexpr std::string_view operation_id = "analysis.validate_result";
    static constexpr std::string_view schema_id = "qcae.operation.analysis.validate_result.v1";
    static OperationDefinition definition() {
        return {"analysis.validate_result", 1, "qcae.operation.analysis.validate_result.v1",
                OperationEffect::auxiliary_write,
                {true, true, true, true, true},
                {
                    {1, "run_id", "string", {}, true, false}
                }};
    }

    static Result<AnalysisValidateResultInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 1> allowed{"run_id"};
        static constexpr std::array<std::string_view, 1> required{"run_id"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto run_id = wire::string_value(fields.at("run_id"), "input.run_id");
        if (!run_id.ok()) {
            return {run_id.status, std::nullopt, run_id.error};
        }
        AnalysisValidateResultInput input{*run_id.value};
        wire::observe_input_copy(input, input.run_id);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const AnalysisValidateResultInput& input) {
        Value::Object object;
        object.emplace("run_id", Value(input.run_id));
        wire::observe_key("run_id");
        return Value(std::move(object));
    }
};

struct ArtifactGetInput {
    std::string artifact_id{};
};

template <> struct InputTraits<ArtifactGetInput> {
    static constexpr std::string_view operation_id = "artifact.get";
    static constexpr std::string_view schema_id = "qcae.operation.artifact.get.v1";
    static OperationDefinition definition() {
        return {"artifact.get", 1, "qcae.operation.artifact.get.v1",
                OperationEffect::read_only,
                {true, true, false, false, false},
                {
                    {1, "artifact_id", "string", {}, true, false}
                }};
    }

    static Result<ArtifactGetInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 1> allowed{"artifact_id"};
        static constexpr std::array<std::string_view, 1> required{"artifact_id"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto artifact_id = wire::string_value(fields.at("artifact_id"), "input.artifact_id");
        if (!artifact_id.ok()) {
            return {artifact_id.status, std::nullopt, artifact_id.error};
        }
        ArtifactGetInput input{*artifact_id.value};
        wire::observe_input_copy(input, input.artifact_id);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const ArtifactGetInput& input) {
        Value::Object object;
        object.emplace("artifact_id", Value(input.artifact_id));
        wire::observe_key("artifact_id");
        return Value(std::move(object));
    }
};

struct ArtifactReconcileInput {
    std::string artifact_id{};
};

template <> struct InputTraits<ArtifactReconcileInput> {
    static constexpr std::string_view operation_id = "artifact.reconcile";
    static constexpr std::string_view schema_id = "qcae.operation.artifact.reconcile.v1";
    static OperationDefinition definition() {
        return {"artifact.reconcile", 1, "qcae.operation.artifact.reconcile.v1",
                OperationEffect::auxiliary_write,
                {true, true, true, true, false},
                {
                    {1, "artifact_id", "string", {}, true, false}
                }};
    }

    static Result<ArtifactReconcileInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 1> allowed{"artifact_id"};
        static constexpr std::array<std::string_view, 1> required{"artifact_id"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto artifact_id = wire::string_value(fields.at("artifact_id"), "input.artifact_id");
        if (!artifact_id.ok()) {
            return {artifact_id.status, std::nullopt, artifact_id.error};
        }
        ArtifactReconcileInput input{*artifact_id.value};
        wire::observe_input_copy(input, input.artifact_id);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const ArtifactReconcileInput& input) {
        Value::Object object;
        object.emplace("artifact_id", Value(input.artifact_id));
        wire::observe_key("artifact_id");
        return Value(std::move(object));
    }
};

struct BeamAssignSectionInput {
    std::vector<EntityId> beam_ids{};
    EntityId section_id{};
};

template <> struct InputTraits<BeamAssignSectionInput> {
    static constexpr std::string_view operation_id = "beam.assign_section";
    static constexpr std::string_view schema_id = "qcae.operation.beam.assign_section.v1";
    static OperationDefinition definition() {
        return {"beam.assign_section", 1, "qcae.operation.beam.assign_section.v1",
                OperationEffect::document_write,
                {true, true, true, true, false},
                {
                    {1, "beam_ids", "entity_id_array", {}, true, false},
                    {2, "section_id", "entity_id", {}, true, false}
                }};
    }

    static Result<BeamAssignSectionInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 2> allowed{"beam_ids", "section_id"};
        static constexpr std::array<std::string_view, 2> required{"beam_ids", "section_id"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto beam_ids = wire::entity_id_array(fields.at("beam_ids"), "input.beam_ids");
        if (!beam_ids.ok()) {
            return {beam_ids.status, std::nullopt, beam_ids.error};
        }
        const auto section_id = wire::entity_id(fields.at("section_id"), "input.section_id");
        if (!section_id.ok()) {
            return {section_id.status, std::nullopt, section_id.error};
        }
        BeamAssignSectionInput input{*beam_ids.value, *section_id.value};
        wire::observe_input_copy(input, input.beam_ids, input.section_id);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const BeamAssignSectionInput& input) {
        Value::Object object;
        object.emplace("beam_ids", wire::to_value(input.beam_ids));
        wire::observe_key("beam_ids");
        object.emplace("section_id", Value(input.section_id.value));
        wire::observe_key("section_id");
        return Value(std::move(object));
    }
};

struct ConstraintCreateInput {
    std::vector<EntityId> node_ids{};
    std::string dofs{};
};

template <> struct InputTraits<ConstraintCreateInput> {
    static constexpr std::string_view operation_id = "constraint.create";
    static constexpr std::string_view schema_id = "qcae.operation.constraint.create.v1";
    static OperationDefinition definition() {
        return {"constraint.create", 1, "qcae.operation.constraint.create.v1",
                OperationEffect::document_write,
                {true, true, true, true, false},
                {
                    {1, "node_ids", "entity_id_array", {}, true, false},
                    {2, "dofs", "string", {}, true, false}
                }};
    }

    static Result<ConstraintCreateInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 2> allowed{"node_ids", "dofs"};
        static constexpr std::array<std::string_view, 2> required{"node_ids", "dofs"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto node_ids = wire::entity_id_array(fields.at("node_ids"), "input.node_ids");
        if (!node_ids.ok()) {
            return {node_ids.status, std::nullopt, node_ids.error};
        }
        const auto dofs = wire::string_value(fields.at("dofs"), "input.dofs");
        if (!dofs.ok()) {
            return {dofs.status, std::nullopt, dofs.error};
        }
        ConstraintCreateInput input{*node_ids.value, *dofs.value};
        wire::observe_input_copy(input, input.node_ids, input.dofs);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const ConstraintCreateInput& input) {
        Value::Object object;
        object.emplace("node_ids", wire::to_value(input.node_ids));
        wire::observe_key("node_ids");
        object.emplace("dofs", Value(input.dofs));
        wire::observe_key("dofs");
        return Value(std::move(object));
    }
};

struct ForceCreateInput {
    EntityId node_id{};
    Quantity x{};
    Quantity y{};
    Quantity z{};
};

template <> struct InputTraits<ForceCreateInput> {
    static constexpr std::string_view operation_id = "force.create";
    static constexpr std::string_view schema_id = "qcae.operation.force.create.v1";
    static OperationDefinition definition() {
        return {"force.create", 1, "qcae.operation.force.create.v1",
                OperationEffect::document_write,
                {true, true, true, true, false},
                {
                    {1, "node_id", "entity_id", {}, true, false},
                    {2, "x", "quantity", {"N", "kN"}, true, false},
                    {3, "y", "quantity", {"N", "kN"}, true, false},
                    {4, "z", "quantity", {"N", "kN"}, true, false}
                }};
    }

    static Result<ForceCreateInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 4> allowed{"node_id", "x", "y", "z"};
        static constexpr std::array<std::string_view, 4> required{"node_id", "x", "y", "z"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto node_id = wire::entity_id(fields.at("node_id"), "input.node_id");
        if (!node_id.ok()) {
            return {node_id.status, std::nullopt, node_id.error};
        }
        static constexpr std::array<std::string_view, 2> x_units{"N", "kN"};
        const auto x = wire::quantity(fields.at("x"), x_units, "input.x");
        if (!x.ok()) {
            return {x.status, std::nullopt, x.error};
        }
        static constexpr std::array<std::string_view, 2> y_units{"N", "kN"};
        const auto y = wire::quantity(fields.at("y"), y_units, "input.y");
        if (!y.ok()) {
            return {y.status, std::nullopt, y.error};
        }
        static constexpr std::array<std::string_view, 2> z_units{"N", "kN"};
        const auto z = wire::quantity(fields.at("z"), z_units, "input.z");
        if (!z.ok()) {
            return {z.status, std::nullopt, z.error};
        }
        ForceCreateInput input{*node_id.value, *x.value, *y.value, *z.value};
        wire::observe_input_copy(input, input.node_id, input.x, input.y, input.z);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const ForceCreateInput& input) {
        Value::Object object;
        object.emplace("node_id", Value(input.node_id.value));
        wire::observe_key("node_id");
        object.emplace("x", wire::to_value(input.x));
        wire::observe_key("x");
        object.emplace("y", wire::to_value(input.y));
        wire::observe_key("y");
        object.emplace("z", wire::to_value(input.z));
        wire::observe_key("z");
        return Value(std::move(object));
    }
};

struct ForcePreviewVectorInput {
    EntityId force_id{};
    Quantity x{};
    Quantity y{};
    Quantity z{};
};

template <> struct InputTraits<ForcePreviewVectorInput> {
    static constexpr std::string_view operation_id = "force.preview_vector";
    static constexpr std::string_view schema_id = "qcae.operation.force.preview_vector.v1";
    static OperationDefinition definition() {
        return {"force.preview_vector", 1, "qcae.operation.force.preview_vector.v1",
                OperationEffect::preview,
                {true, true, true, false, false},
                {
                    {1, "force_id", "entity_id", {}, true, false},
                    {2, "x", "quantity", {"N", "kN"}, true, false},
                    {3, "y", "quantity", {"N", "kN"}, true, false},
                    {4, "z", "quantity", {"N", "kN"}, true, false}
                }};
    }

    static Result<ForcePreviewVectorInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 4> allowed{"force_id", "x", "y", "z"};
        static constexpr std::array<std::string_view, 4> required{"force_id", "x", "y", "z"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto force_id = wire::entity_id(fields.at("force_id"), "input.force_id");
        if (!force_id.ok()) {
            return {force_id.status, std::nullopt, force_id.error};
        }
        static constexpr std::array<std::string_view, 2> x_units{"N", "kN"};
        const auto x = wire::quantity(fields.at("x"), x_units, "input.x");
        if (!x.ok()) {
            return {x.status, std::nullopt, x.error};
        }
        static constexpr std::array<std::string_view, 2> y_units{"N", "kN"};
        const auto y = wire::quantity(fields.at("y"), y_units, "input.y");
        if (!y.ok()) {
            return {y.status, std::nullopt, y.error};
        }
        static constexpr std::array<std::string_view, 2> z_units{"N", "kN"};
        const auto z = wire::quantity(fields.at("z"), z_units, "input.z");
        if (!z.ok()) {
            return {z.status, std::nullopt, z.error};
        }
        ForcePreviewVectorInput input{*force_id.value, *x.value, *y.value, *z.value};
        wire::observe_input_copy(input, input.force_id, input.x, input.y, input.z);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const ForcePreviewVectorInput& input) {
        Value::Object object;
        object.emplace("force_id", Value(input.force_id.value));
        wire::observe_key("force_id");
        object.emplace("x", wire::to_value(input.x));
        wire::observe_key("x");
        object.emplace("y", wire::to_value(input.y));
        wire::observe_key("y");
        object.emplace("z", wire::to_value(input.z));
        wire::observe_key("z");
        return Value(std::move(object));
    }
};

struct ForceSetVectorInput {
    EntityId force_id{};
    Quantity x{};
    Quantity y{};
    Quantity z{};
};

template <> struct InputTraits<ForceSetVectorInput> {
    static constexpr std::string_view operation_id = "force.set_vector";
    static constexpr std::string_view schema_id = "qcae.operation.force.set_vector.v1";
    static OperationDefinition definition() {
        return {"force.set_vector", 1, "qcae.operation.force.set_vector.v1",
                OperationEffect::document_write,
                {true, true, true, true, false},
                {
                    {1, "force_id", "entity_id", {}, true, false},
                    {2, "x", "quantity", {"N", "kN"}, true, false},
                    {3, "y", "quantity", {"N", "kN"}, true, false},
                    {4, "z", "quantity", {"N", "kN"}, true, false}
                }};
    }

    static Result<ForceSetVectorInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 4> allowed{"force_id", "x", "y", "z"};
        static constexpr std::array<std::string_view, 4> required{"force_id", "x", "y", "z"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto force_id = wire::entity_id(fields.at("force_id"), "input.force_id");
        if (!force_id.ok()) {
            return {force_id.status, std::nullopt, force_id.error};
        }
        static constexpr std::array<std::string_view, 2> x_units{"N", "kN"};
        const auto x = wire::quantity(fields.at("x"), x_units, "input.x");
        if (!x.ok()) {
            return {x.status, std::nullopt, x.error};
        }
        static constexpr std::array<std::string_view, 2> y_units{"N", "kN"};
        const auto y = wire::quantity(fields.at("y"), y_units, "input.y");
        if (!y.ok()) {
            return {y.status, std::nullopt, y.error};
        }
        static constexpr std::array<std::string_view, 2> z_units{"N", "kN"};
        const auto z = wire::quantity(fields.at("z"), z_units, "input.z");
        if (!z.ok()) {
            return {z.status, std::nullopt, z.error};
        }
        ForceSetVectorInput input{*force_id.value, *x.value, *y.value, *z.value};
        wire::observe_input_copy(input, input.force_id, input.x, input.y, input.z);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const ForceSetVectorInput& input) {
        Value::Object object;
        object.emplace("force_id", Value(input.force_id.value));
        wire::observe_key("force_id");
        object.emplace("x", wire::to_value(input.x));
        wire::observe_key("x");
        object.emplace("y", wire::to_value(input.y));
        wire::observe_key("y");
        object.emplace("z", wire::to_value(input.z));
        wire::observe_key("z");
        return Value(std::move(object));
    }
};

struct GeometryCreateLineInput {
    std::array<double, 3> start_mm{};
    std::array<double, 3> end_mm{};
};

template <> struct InputTraits<GeometryCreateLineInput> {
    static constexpr std::string_view operation_id = "geometry.create_line";
    static constexpr std::string_view schema_id = "qcae.operation.geometry.create_line.v1";
    static OperationDefinition definition() {
        return {"geometry.create_line", 1, "qcae.operation.geometry.create_line.v1",
                OperationEffect::document_write,
                {true, true, true, true, false},
                {
                    {1, "start_mm", "vector3_mm", {"mm"}, true, false},
                    {2, "end_mm", "vector3_mm", {"mm"}, true, false}
                }};
    }

    static Result<GeometryCreateLineInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 2> allowed{"start_mm", "end_mm"};
        static constexpr std::array<std::string_view, 2> required{"start_mm", "end_mm"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto start_mm = wire::vector3(fields.at("start_mm"), "input.start_mm");
        if (!start_mm.ok()) {
            return {start_mm.status, std::nullopt, start_mm.error};
        }
        const auto end_mm = wire::vector3(fields.at("end_mm"), "input.end_mm");
        if (!end_mm.ok()) {
            return {end_mm.status, std::nullopt, end_mm.error};
        }
        GeometryCreateLineInput input{*start_mm.value, *end_mm.value};
        wire::observe_input_copy(input, input.start_mm, input.end_mm);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const GeometryCreateLineInput& input) {
        Value::Object object;
        object.emplace("start_mm", wire::to_value(input.start_mm));
        wire::observe_key("start_mm");
        object.emplace("end_mm", wire::to_value(input.end_mm));
        wire::observe_key("end_mm");
        return Value(std::move(object));
    }
};

struct GeometryEvaluateLineInput {
    EntityId geometry_id{};
    double u{};
};

template <> struct InputTraits<GeometryEvaluateLineInput> {
    static constexpr std::string_view operation_id = "geometry.evaluate_line";
    static constexpr std::string_view schema_id = "qcae.operation.geometry.evaluate_line.v1";
    static OperationDefinition definition() {
        return {"geometry.evaluate_line", 1, "qcae.operation.geometry.evaluate_line.v1",
                OperationEffect::read_only,
                {true, true, false, false, false},
                {
                    {1, "geometry_id", "entity_id", {}, true, false},
                    {2, "u", "finite_number", {"1"}, true, false}
                }};
    }

    static Result<GeometryEvaluateLineInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 2> allowed{"geometry_id", "u"};
        static constexpr std::array<std::string_view, 2> required{"geometry_id", "u"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto geometry_id = wire::entity_id(fields.at("geometry_id"), "input.geometry_id");
        if (!geometry_id.ok()) {
            return {geometry_id.status, std::nullopt, geometry_id.error};
        }
        const auto u = wire::finite_number(fields.at("u"), "input.u");
        if (!u.ok()) {
            return {u.status, std::nullopt, u.error};
        }
        GeometryEvaluateLineInput input{*geometry_id.value, *u.value};
        wire::observe_input_copy(input, input.geometry_id, input.u);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const GeometryEvaluateLineInput& input) {
        Value::Object object;
        object.emplace("geometry_id", Value(input.geometry_id.value));
        wire::observe_key("geometry_id");
        object.emplace("u", Value(input.u));
        wire::observe_key("u");
        return Value(std::move(object));
    }
};

struct GeometryMoveEndpointInput {
    EntityId geometry_id{};
    std::array<double, 3> end_mm{};
};

template <> struct InputTraits<GeometryMoveEndpointInput> {
    static constexpr std::string_view operation_id = "geometry.move_endpoint";
    static constexpr std::string_view schema_id = "qcae.operation.geometry.move_endpoint.v1";
    static OperationDefinition definition() {
        return {"geometry.move_endpoint", 1, "qcae.operation.geometry.move_endpoint.v1",
                OperationEffect::document_write,
                {true, true, true, true, false},
                {
                    {1, "geometry_id", "entity_id", {}, true, false},
                    {2, "end_mm", "vector3_mm", {"mm"}, true, false}
                }};
    }

    static Result<GeometryMoveEndpointInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 2> allowed{"geometry_id", "end_mm"};
        static constexpr std::array<std::string_view, 2> required{"geometry_id", "end_mm"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto geometry_id = wire::entity_id(fields.at("geometry_id"), "input.geometry_id");
        if (!geometry_id.ok()) {
            return {geometry_id.status, std::nullopt, geometry_id.error};
        }
        const auto end_mm = wire::vector3(fields.at("end_mm"), "input.end_mm");
        if (!end_mm.ok()) {
            return {end_mm.status, std::nullopt, end_mm.error};
        }
        GeometryMoveEndpointInput input{*geometry_id.value, *end_mm.value};
        wire::observe_input_copy(input, input.geometry_id, input.end_mm);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const GeometryMoveEndpointInput& input) {
        Value::Object object;
        object.emplace("geometry_id", Value(input.geometry_id.value));
        wire::observe_key("geometry_id");
        object.emplace("end_mm", wire::to_value(input.end_mm));
        wire::observe_key("end_mm");
        return Value(std::move(object));
    }
};

struct LoadCaseCreateInput {
    std::string name{};
    std::vector<EntityId> force_ids{};
    std::vector<EntityId> constraint_ids{};
};

template <> struct InputTraits<LoadCaseCreateInput> {
    static constexpr std::string_view operation_id = "load_case.create";
    static constexpr std::string_view schema_id = "qcae.operation.load_case.create.v1";
    static OperationDefinition definition() {
        return {"load_case.create", 1, "qcae.operation.load_case.create.v1",
                OperationEffect::document_write,
                {true, true, true, true, false},
                {
                    {1, "name", "string", {}, true, false},
                    {2, "force_ids", "entity_id_array", {}, true, true},
                    {3, "constraint_ids", "entity_id_array", {}, true, true}
                }};
    }

    static Result<LoadCaseCreateInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 3> allowed{"name", "force_ids", "constraint_ids"};
        static constexpr std::array<std::string_view, 3> required{"name", "force_ids", "constraint_ids"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto name = wire::string_value(fields.at("name"), "input.name");
        if (!name.ok()) {
            return {name.status, std::nullopt, name.error};
        }
        const auto force_ids = wire::entity_id_array(fields.at("force_ids"), "input.force_ids", true);
        if (!force_ids.ok()) {
            return {force_ids.status, std::nullopt, force_ids.error};
        }
        const auto constraint_ids = wire::entity_id_array(fields.at("constraint_ids"), "input.constraint_ids", true);
        if (!constraint_ids.ok()) {
            return {constraint_ids.status, std::nullopt, constraint_ids.error};
        }
        LoadCaseCreateInput input{*name.value, *force_ids.value, *constraint_ids.value};
        wire::observe_input_copy(input, input.name, input.force_ids, input.constraint_ids);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const LoadCaseCreateInput& input) {
        Value::Object object;
        object.emplace("name", Value(input.name));
        wire::observe_key("name");
        object.emplace("force_ids", wire::to_value(input.force_ids));
        wire::observe_key("force_ids");
        object.emplace("constraint_ids", wire::to_value(input.constraint_ids));
        wire::observe_key("constraint_ids");
        return Value(std::move(object));
    }
};

struct LoadCaseSetReferencesInput {
    EntityId load_case_id{};
    std::vector<EntityId> force_ids{};
    std::vector<EntityId> constraint_ids{};
};

template <> struct InputTraits<LoadCaseSetReferencesInput> {
    static constexpr std::string_view operation_id = "load_case.set_references";
    static constexpr std::string_view schema_id = "qcae.operation.load_case.set_references.v1";
    static OperationDefinition definition() {
        return {"load_case.set_references", 1, "qcae.operation.load_case.set_references.v1",
                OperationEffect::document_write,
                {true, true, true, true, false},
                {
                    {1, "load_case_id", "entity_id", {}, true, false},
                    {2, "force_ids", "entity_id_array", {}, true, true},
                    {3, "constraint_ids", "entity_id_array", {}, true, true}
                }};
    }

    static Result<LoadCaseSetReferencesInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 3> allowed{"load_case_id", "force_ids", "constraint_ids"};
        static constexpr std::array<std::string_view, 3> required{"load_case_id", "force_ids", "constraint_ids"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto load_case_id = wire::entity_id(fields.at("load_case_id"), "input.load_case_id");
        if (!load_case_id.ok()) {
            return {load_case_id.status, std::nullopt, load_case_id.error};
        }
        const auto force_ids = wire::entity_id_array(fields.at("force_ids"), "input.force_ids", true);
        if (!force_ids.ok()) {
            return {force_ids.status, std::nullopt, force_ids.error};
        }
        const auto constraint_ids = wire::entity_id_array(fields.at("constraint_ids"), "input.constraint_ids", true);
        if (!constraint_ids.ok()) {
            return {constraint_ids.status, std::nullopt, constraint_ids.error};
        }
        LoadCaseSetReferencesInput input{*load_case_id.value, *force_ids.value, *constraint_ids.value};
        wire::observe_input_copy(input, input.load_case_id, input.force_ids, input.constraint_ids);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const LoadCaseSetReferencesInput& input) {
        Value::Object object;
        object.emplace("load_case_id", Value(input.load_case_id.value));
        wire::observe_key("load_case_id");
        object.emplace("force_ids", wire::to_value(input.force_ids));
        wire::observe_key("force_ids");
        object.emplace("constraint_ids", wire::to_value(input.constraint_ids));
        wire::observe_key("constraint_ids");
        return Value(std::move(object));
    }
};

struct MaterialCreateInput {
    std::string name{};
    Quantity young_modulus{};
    std::optional<double> poisson_ratio{};
};

template <> struct InputTraits<MaterialCreateInput> {
    static constexpr std::string_view operation_id = "material.create";
    static constexpr std::string_view schema_id = "qcae.operation.material.create.v1";
    static OperationDefinition definition() {
        return {"material.create", 1, "qcae.operation.material.create.v1",
                OperationEffect::document_write,
                {true, true, true, true, false},
                {
                    {1, "name", "string", {}, true, false},
                    {2, "young_modulus", "quantity", {"Pa", "kPa", "MPa", "GPa"}, true, false},
                    {3, "poisson_ratio", "finite_number", {"1"}, false, false}
                }};
    }

    static Result<MaterialCreateInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 3> allowed{"name", "young_modulus", "poisson_ratio"};
        static constexpr std::array<std::string_view, 2> required{"name", "young_modulus"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto name = wire::string_value(fields.at("name"), "input.name");
        if (!name.ok()) {
            return {name.status, std::nullopt, name.error};
        }
        static constexpr std::array<std::string_view, 4> young_modulus_units{"Pa", "kPa", "MPa", "GPa"};
        const auto young_modulus = wire::quantity(fields.at("young_modulus"), young_modulus_units, "input.young_modulus");
        if (!young_modulus.ok()) {
            return {young_modulus.status, std::nullopt, young_modulus.error};
        }
        std::optional<double> poisson_ratio;
        if (const auto found = fields.find("poisson_ratio"); found != fields.end()) {
            const auto poisson_ratio_decoded = wire::finite_number(found->second, "input.poisson_ratio");
            if (!poisson_ratio_decoded.ok()) {
                return {poisson_ratio_decoded.status, std::nullopt, poisson_ratio_decoded.error};
            }
            poisson_ratio = *poisson_ratio_decoded.value;
            wire::observe_input_copy(*poisson_ratio, *poisson_ratio);
        }
        MaterialCreateInput input{*name.value, *young_modulus.value, poisson_ratio};
        wire::observe_input_copy(input, input.name, input.young_modulus, input.poisson_ratio);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const MaterialCreateInput& input) {
        Value::Object object;
        object.emplace("name", Value(input.name));
        wire::observe_key("name");
        object.emplace("young_modulus", wire::to_value(input.young_modulus));
        wire::observe_key("young_modulus");
        if (input.poisson_ratio) {
            object.emplace("poisson_ratio", Value(*input.poisson_ratio));
            wire::observe_key("poisson_ratio");
        }
        return Value(std::move(object));
    }
};

struct MaterialSetYoungModulusInput {
    EntityId entity_id{};
    Quantity young_modulus{};
};

template <> struct InputTraits<MaterialSetYoungModulusInput> {
    static constexpr std::string_view operation_id = "material.set_young_modulus";
    static constexpr std::string_view schema_id = "qcae.operation.material.set_young_modulus.v1";
    static OperationDefinition definition() {
        return {"material.set_young_modulus", 1, "qcae.operation.material.set_young_modulus.v1",
                OperationEffect::document_write,
                {true, true, true, true, false},
                {
                    {1, "entity_id", "entity_id", {}, true, false},
                    {2, "young_modulus", "quantity", {"Pa", "kPa", "MPa", "GPa"}, true, false}
                }};
    }

    static Result<MaterialSetYoungModulusInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 2> allowed{"entity_id", "young_modulus"};
        static constexpr std::array<std::string_view, 2> required{"entity_id", "young_modulus"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto entity_id = wire::entity_id(fields.at("entity_id"), "input.entity_id");
        if (!entity_id.ok()) {
            return {entity_id.status, std::nullopt, entity_id.error};
        }
        static constexpr std::array<std::string_view, 4> young_modulus_units{"Pa", "kPa", "MPa", "GPa"};
        const auto young_modulus = wire::quantity(fields.at("young_modulus"), young_modulus_units, "input.young_modulus");
        if (!young_modulus.ok()) {
            return {young_modulus.status, std::nullopt, young_modulus.error};
        }
        MaterialSetYoungModulusInput input{*entity_id.value, *young_modulus.value};
        wire::observe_input_copy(input, input.entity_id, input.young_modulus);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const MaterialSetYoungModulusInput& input) {
        Value::Object object;
        object.emplace("entity_id", Value(input.entity_id.value));
        wire::observe_key("entity_id");
        object.emplace("young_modulus", wire::to_value(input.young_modulus));
        wire::observe_key("young_modulus");
        return Value(std::move(object));
    }
};

struct MeshCreateTri3Input {
    std::vector<EntityId> node_ids{};
    EntityId mesh_id{};
};

template <> struct InputTraits<MeshCreateTri3Input> {
    static constexpr std::string_view operation_id = "mesh.create_tri3";
    static constexpr std::string_view schema_id = "qcae.operation.mesh.create_tri3.v1";
    static OperationDefinition definition() {
        return {"mesh.create_tri3", 1, "qcae.operation.mesh.create_tri3.v1",
                OperationEffect::document_write,
                {true, true, true, true, false},
                {
                    {1, "node_ids", "entity_id_array", {}, true, false},
                    {2, "mesh_id", "entity_id", {}, true, false}
                }};
    }

    static Result<MeshCreateTri3Input> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 2> allowed{"node_ids", "mesh_id"};
        static constexpr std::array<std::string_view, 2> required{"node_ids", "mesh_id"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto node_ids = wire::entity_id_array(fields.at("node_ids"), "input.node_ids");
        if (!node_ids.ok()) {
            return {node_ids.status, std::nullopt, node_ids.error};
        }
        const auto mesh_id = wire::entity_id(fields.at("mesh_id"), "input.mesh_id");
        if (!mesh_id.ok()) {
            return {mesh_id.status, std::nullopt, mesh_id.error};
        }
        MeshCreateTri3Input input{*node_ids.value, *mesh_id.value};
        wire::observe_input_copy(input, input.node_ids, input.mesh_id);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const MeshCreateTri3Input& input) {
        Value::Object object;
        object.emplace("node_ids", wire::to_value(input.node_ids));
        wire::observe_key("node_ids");
        object.emplace("mesh_id", Value(input.mesh_id.value));
        wire::observe_key("mesh_id");
        return Value(std::move(object));
    }
};

struct MeshGenerateLineInput {
    EntityId geometry_id{};
    std::uint32_t segments{};
};

template <> struct InputTraits<MeshGenerateLineInput> {
    static constexpr std::string_view operation_id = "mesh.generate_line";
    static constexpr std::string_view schema_id = "qcae.operation.mesh.generate_line.v1";
    static OperationDefinition definition() {
        return {"mesh.generate_line", 1, "qcae.operation.mesh.generate_line.v1",
                OperationEffect::background_task,
                {true, true, true, true, false},
                {
                    {1, "geometry_id", "entity_id", {}, true, false},
                    {2, "segments", "positive_uint32", {}, true, false}
                }};
    }

    static Result<MeshGenerateLineInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 2> allowed{"geometry_id", "segments"};
        static constexpr std::array<std::string_view, 2> required{"geometry_id", "segments"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto geometry_id = wire::entity_id(fields.at("geometry_id"), "input.geometry_id");
        if (!geometry_id.ok()) {
            return {geometry_id.status, std::nullopt, geometry_id.error};
        }
        const auto segments = wire::positive_uint32(fields.at("segments"), "input.segments");
        if (!segments.ok()) {
            return {segments.status, std::nullopt, segments.error};
        }
        MeshGenerateLineInput input{*geometry_id.value, *segments.value};
        wire::observe_input_copy(input, input.geometry_id, input.segments);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const MeshGenerateLineInput& input) {
        Value::Object object;
        object.emplace("geometry_id", Value(input.geometry_id.value));
        wire::observe_key("geometry_id");
        object.emplace("segments", Value(static_cast<std::int64_t>(input.segments)));
        wire::observe_key("segments");
        return Value(std::move(object));
    }
};

struct MeshRegenerateLineInput {
    EntityId mesh_id{};
    std::uint32_t segments{};
    std::string replacement_policy{};
};

template <> struct InputTraits<MeshRegenerateLineInput> {
    static constexpr std::string_view operation_id = "mesh.regenerate_line";
    static constexpr std::string_view schema_id = "qcae.operation.mesh.regenerate_line.v1";
    static OperationDefinition definition() {
        return {"mesh.regenerate_line", 1, "qcae.operation.mesh.regenerate_line.v1",
                OperationEffect::background_task,
                {true, true, true, true, false},
                {
                    {1, "mesh_id", "entity_id", {}, true, false},
                    {2, "segments", "positive_uint32", {}, true, false},
                    {3, "replacement_policy", "string", {}, true, false}
                }};
    }

    static Result<MeshRegenerateLineInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 3> allowed{"mesh_id", "segments", "replacement_policy"};
        static constexpr std::array<std::string_view, 3> required{"mesh_id", "segments", "replacement_policy"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto mesh_id = wire::entity_id(fields.at("mesh_id"), "input.mesh_id");
        if (!mesh_id.ok()) {
            return {mesh_id.status, std::nullopt, mesh_id.error};
        }
        const auto segments = wire::positive_uint32(fields.at("segments"), "input.segments");
        if (!segments.ok()) {
            return {segments.status, std::nullopt, segments.error};
        }
        const auto replacement_policy = wire::string_value(fields.at("replacement_policy"), "input.replacement_policy");
        if (!replacement_policy.ok()) {
            return {replacement_policy.status, std::nullopt, replacement_policy.error};
        }
        MeshRegenerateLineInput input{*mesh_id.value, *segments.value, *replacement_policy.value};
        wire::observe_input_copy(input, input.mesh_id, input.segments, input.replacement_policy);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const MeshRegenerateLineInput& input) {
        Value::Object object;
        object.emplace("mesh_id", Value(input.mesh_id.value));
        wire::observe_key("mesh_id");
        object.emplace("segments", Value(static_cast<std::int64_t>(input.segments)));
        wire::observe_key("segments");
        object.emplace("replacement_policy", Value(input.replacement_policy));
        wire::observe_key("replacement_policy");
        return Value(std::move(object));
    }
};

struct ModelExportInput {
    EntityId analysis_id{};
    std::string output_directory{};
};

template <> struct InputTraits<ModelExportInput> {
    static constexpr std::string_view operation_id = "model.export";
    static constexpr std::string_view schema_id = "qcae.operation.model.export.v1";
    static OperationDefinition definition() {
        return {"model.export", 1, "qcae.operation.model.export.v1",
                OperationEffect::background_task,
                {true, true, true, true, true},
                {
                    {1, "analysis_id", "entity_id", {}, true, false},
                    {2, "output_directory", "string", {}, true, false}
                }};
    }

    static Result<ModelExportInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 2> allowed{"analysis_id", "output_directory"};
        static constexpr std::array<std::string_view, 2> required{"analysis_id", "output_directory"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto analysis_id = wire::entity_id(fields.at("analysis_id"), "input.analysis_id");
        if (!analysis_id.ok()) {
            return {analysis_id.status, std::nullopt, analysis_id.error};
        }
        const auto output_directory = wire::string_value(fields.at("output_directory"), "input.output_directory");
        if (!output_directory.ok()) {
            return {output_directory.status, std::nullopt, output_directory.error};
        }
        ModelExportInput input{*analysis_id.value, *output_directory.value};
        wire::observe_input_copy(input, input.analysis_id, input.output_directory);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const ModelExportInput& input) {
        Value::Object object;
        object.emplace("analysis_id", Value(input.analysis_id.value));
        wire::observe_key("analysis_id");
        object.emplace("output_directory", Value(input.output_directory));
        wire::observe_key("output_directory");
        return Value(std::move(object));
    }
};

struct NastranUiInput {
};

template <> struct InputTraits<NastranUiInput> {
    static constexpr std::string_view operation_id = "nastran.ui";
    static constexpr std::string_view schema_id = "qcae.operation.nastran.ui.v1";
    static OperationDefinition definition() {
        return {"nastran.ui", 1, "qcae.operation.nastran.ui.v1",
                OperationEffect::read_only,
                {false, false, false, false, false},
                {
                }};
    }

    static Result<NastranUiInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 0> allowed{};
        static constexpr std::array<std::string_view, 0> required{};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        NastranUiInput input{};
        wire::observe_input_copy(input);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const NastranUiInput&) {
        Value::Object object;
        return Value(std::move(object));
    }
};

struct NodeMoveInput {
    EntityId entity_id{};
    std::array<double, 3> position_mm{};
};

template <> struct InputTraits<NodeMoveInput> {
    static constexpr std::string_view operation_id = "node.move";
    static constexpr std::string_view schema_id = "qcae.operation.node.move.v1";
    static OperationDefinition definition() {
        return {"node.move", 1, "qcae.operation.node.move.v1",
                OperationEffect::document_write,
                {true, true, true, true, false},
                {
                    {1, "entity_id", "entity_id", {}, true, false},
                    {2, "position_mm", "vector3_mm", {"mm"}, true, false}
                }};
    }

    static Result<NodeMoveInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 2> allowed{"entity_id", "position_mm"};
        static constexpr std::array<std::string_view, 2> required{"entity_id", "position_mm"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto entity_id = wire::entity_id(fields.at("entity_id"), "input.entity_id");
        if (!entity_id.ok()) {
            return {entity_id.status, std::nullopt, entity_id.error};
        }
        const auto position_mm = wire::vector3(fields.at("position_mm"), "input.position_mm");
        if (!position_mm.ok()) {
            return {position_mm.status, std::nullopt, position_mm.error};
        }
        NodeMoveInput input{*entity_id.value, *position_mm.value};
        wire::observe_input_copy(input, input.entity_id, input.position_mm);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const NodeMoveInput& input) {
        Value::Object object;
        object.emplace("entity_id", Value(input.entity_id.value));
        wire::observe_key("entity_id");
        object.emplace("position_mm", wire::to_value(input.position_mm));
        wire::observe_key("position_mm");
        return Value(std::move(object));
    }
};

struct ProjectMigrateProfileInput {
    std::string source_path{};
    std::string old_profile_id{};
    std::string old_profile_version{};
    std::string old_definition_digest{};
};

template <> struct InputTraits<ProjectMigrateProfileInput> {
    static constexpr std::string_view operation_id = "project.migrate_profile";
    static constexpr std::string_view schema_id = "qcae.operation.project.migrate_profile.v1";
    static OperationDefinition definition() {
        return {"project.migrate_profile", 1, "qcae.operation.project.migrate_profile.v1",
                OperationEffect::document_write,
                {false, false, false, true, true},
                {
                    {1, "source_path", "string", {}, true, false},
                    {2, "old_profile_id", "string", {}, true, false},
                    {3, "old_profile_version", "string", {}, true, false},
                    {4, "old_definition_digest", "string", {}, true, false}
                }};
    }

    static Result<ProjectMigrateProfileInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 4> allowed{"source_path", "old_profile_id", "old_profile_version", "old_definition_digest"};
        static constexpr std::array<std::string_view, 4> required{"source_path", "old_profile_id", "old_profile_version", "old_definition_digest"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto source_path = wire::string_value(fields.at("source_path"), "input.source_path");
        if (!source_path.ok()) {
            return {source_path.status, std::nullopt, source_path.error};
        }
        const auto old_profile_id = wire::string_value(fields.at("old_profile_id"), "input.old_profile_id");
        if (!old_profile_id.ok()) {
            return {old_profile_id.status, std::nullopt, old_profile_id.error};
        }
        const auto old_profile_version = wire::string_value(fields.at("old_profile_version"), "input.old_profile_version");
        if (!old_profile_version.ok()) {
            return {old_profile_version.status, std::nullopt, old_profile_version.error};
        }
        const auto old_definition_digest = wire::string_value(fields.at("old_definition_digest"), "input.old_definition_digest");
        if (!old_definition_digest.ok()) {
            return {old_definition_digest.status, std::nullopt, old_definition_digest.error};
        }
        ProjectMigrateProfileInput input{*source_path.value, *old_profile_id.value, *old_profile_version.value, *old_definition_digest.value};
        wire::observe_input_copy(input, input.source_path, input.old_profile_id, input.old_profile_version, input.old_definition_digest);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const ProjectMigrateProfileInput& input) {
        Value::Object object;
        object.emplace("source_path", Value(input.source_path));
        wire::observe_key("source_path");
        object.emplace("old_profile_id", Value(input.old_profile_id));
        wire::observe_key("old_profile_id");
        object.emplace("old_profile_version", Value(input.old_profile_version));
        wire::observe_key("old_profile_version");
        object.emplace("old_definition_digest", Value(input.old_definition_digest));
        wire::observe_key("old_definition_digest");
        return Value(std::move(object));
    }
};

struct ResultsGetInput {
    std::string result_id{};
};

template <> struct InputTraits<ResultsGetInput> {
    static constexpr std::string_view operation_id = "results.get";
    static constexpr std::string_view schema_id = "qcae.operation.results.get.v1";
    static OperationDefinition definition() {
        return {"results.get", 1, "qcae.operation.results.get.v1",
                OperationEffect::read_only,
                {true, true, false, false, false},
                {
                    {1, "result_id", "string", {}, true, false}
                }};
    }

    static Result<ResultsGetInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 1> allowed{"result_id"};
        static constexpr std::array<std::string_view, 1> required{"result_id"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto result_id = wire::string_value(fields.at("result_id"), "input.result_id");
        if (!result_id.ok()) {
            return {result_id.status, std::nullopt, result_id.error};
        }
        ResultsGetInput input{*result_id.value};
        wire::observe_input_copy(input, input.result_id);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const ResultsGetInput& input) {
        Value::Object object;
        object.emplace("result_id", Value(input.result_id));
        wire::observe_key("result_id");
        return Value(std::move(object));
    }
};

struct ResultsReadFixtureInput {
    std::string artifact_id{};
    std::string fixture_json{};
};

template <> struct InputTraits<ResultsReadFixtureInput> {
    static constexpr std::string_view operation_id = "results.read_fixture";
    static constexpr std::string_view schema_id = "qcae.operation.results.read_fixture.v1";
    static OperationDefinition definition() {
        return {"results.read_fixture", 1, "qcae.operation.results.read_fixture.v1",
                OperationEffect::auxiliary_write,
                {true, true, true, true, false},
                {
                    {1, "artifact_id", "string", {}, true, false},
                    {2, "fixture_json", "string", {}, true, false}
                }};
    }

    static Result<ResultsReadFixtureInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 2> allowed{"artifact_id", "fixture_json"};
        static constexpr std::array<std::string_view, 2> required{"artifact_id", "fixture_json"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto artifact_id = wire::string_value(fields.at("artifact_id"), "input.artifact_id");
        if (!artifact_id.ok()) {
            return {artifact_id.status, std::nullopt, artifact_id.error};
        }
        const auto fixture_json = wire::string_value(fields.at("fixture_json"), "input.fixture_json");
        if (!fixture_json.ok()) {
            return {fixture_json.status, std::nullopt, fixture_json.error};
        }
        ResultsReadFixtureInput input{*artifact_id.value, *fixture_json.value};
        wire::observe_input_copy(input, input.artifact_id, input.fixture_json);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const ResultsReadFixtureInput& input) {
        Value::Object object;
        object.emplace("artifact_id", Value(input.artifact_id));
        wire::observe_key("artifact_id");
        object.emplace("fixture_json", Value(input.fixture_json));
        wire::observe_key("fixture_json");
        return Value(std::move(object));
    }
};

struct SectionCreateInput {
    std::string name{};
    EntityId material_id{};
    double area_mm2{};
    double i1_mm4{};
    double i2_mm4{};
    double torsion_mm4{};
};

template <> struct InputTraits<SectionCreateInput> {
    static constexpr std::string_view operation_id = "section.create";
    static constexpr std::string_view schema_id = "qcae.operation.section.create.v1";
    static OperationDefinition definition() {
        return {"section.create", 1, "qcae.operation.section.create.v1",
                OperationEffect::document_write,
                {true, true, true, true, false},
                {
                    {1, "name", "string", {}, true, false},
                    {2, "material_id", "entity_id", {}, true, false},
                    {3, "area_mm2", "finite_number", {"mm2"}, true, false},
                    {4, "i1_mm4", "finite_number", {"mm4"}, true, false},
                    {5, "i2_mm4", "finite_number", {"mm4"}, true, false},
                    {6, "torsion_mm4", "finite_number", {"mm4"}, true, false}
                }};
    }

    static Result<SectionCreateInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 6> allowed{"name", "material_id", "area_mm2", "i1_mm4", "i2_mm4", "torsion_mm4"};
        static constexpr std::array<std::string_view, 6> required{"name", "material_id", "area_mm2", "i1_mm4", "i2_mm4", "torsion_mm4"};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        const auto& fields = **object.value;
        const auto name = wire::string_value(fields.at("name"), "input.name");
        if (!name.ok()) {
            return {name.status, std::nullopt, name.error};
        }
        const auto material_id = wire::entity_id(fields.at("material_id"), "input.material_id");
        if (!material_id.ok()) {
            return {material_id.status, std::nullopt, material_id.error};
        }
        const auto area_mm2 = wire::finite_number(fields.at("area_mm2"), "input.area_mm2");
        if (!area_mm2.ok()) {
            return {area_mm2.status, std::nullopt, area_mm2.error};
        }
        const auto i1_mm4 = wire::finite_number(fields.at("i1_mm4"), "input.i1_mm4");
        if (!i1_mm4.ok()) {
            return {i1_mm4.status, std::nullopt, i1_mm4.error};
        }
        const auto i2_mm4 = wire::finite_number(fields.at("i2_mm4"), "input.i2_mm4");
        if (!i2_mm4.ok()) {
            return {i2_mm4.status, std::nullopt, i2_mm4.error};
        }
        const auto torsion_mm4 = wire::finite_number(fields.at("torsion_mm4"), "input.torsion_mm4");
        if (!torsion_mm4.ok()) {
            return {torsion_mm4.status, std::nullopt, torsion_mm4.error};
        }
        SectionCreateInput input{*name.value, *material_id.value, *area_mm2.value, *i1_mm4.value, *i2_mm4.value, *torsion_mm4.value};
        wire::observe_input_copy(input, input.name, input.material_id, input.area_mm2, input.i1_mm4, input.i2_mm4, input.torsion_mm4);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const SectionCreateInput& input) {
        Value::Object object;
        object.emplace("name", Value(input.name));
        wire::observe_key("name");
        object.emplace("material_id", Value(input.material_id.value));
        wire::observe_key("material_id");
        object.emplace("area_mm2", Value(input.area_mm2));
        wire::observe_key("area_mm2");
        object.emplace("i1_mm4", Value(input.i1_mm4));
        wire::observe_key("i1_mm4");
        object.emplace("i2_mm4", Value(input.i2_mm4));
        wire::observe_key("i2_mm4");
        object.emplace("torsion_mm4", Value(input.torsion_mm4));
        wire::observe_key("torsion_mm4");
        return Value(std::move(object));
    }
};

struct SolverConfigurationInput {
};

template <> struct InputTraits<SolverConfigurationInput> {
    static constexpr std::string_view operation_id = "solver.configuration";
    static constexpr std::string_view schema_id = "qcae.operation.solver.configuration.v1";
    static OperationDefinition definition() {
        return {"solver.configuration", 1, "qcae.operation.solver.configuration.v1",
                OperationEffect::read_only,
                {false, false, false, false, false},
                {
                }};
    }

    static Result<SolverConfigurationInput> from_value(const Value& value) {
        static constexpr std::array<std::string_view, 0> allowed{};
        static constexpr std::array<std::string_view, 0> required{};
        const auto object = wire::object_fields(value, allowed, required, "input");
        if (!object.ok()) {
            return {object.status, std::nullopt, object.error};
        }
        SolverConfigurationInput input{};
        wire::observe_input_copy(input);
        return {Status::success, std::move(input), std::nullopt};
    }

    static Value to_value(const SolverConfigurationInput&) {
        Value::Object object;
        return Value(std::move(object));
    }
};

} // namespace qcae::operations
