// Generated by tools/generate_entities.py; do not edit.
// Semantic schema SHA-256: d0f8a9057d2a09411c09317f817497dbcef7ee90e92960a5650b26da41521203
#pragma once
#include "qcae/document_view.hpp"
#include <algorithm>
#include <cmath>
#include <set>
#include <type_traits>
namespace qcae {
namespace records {
struct GeometryTag;
struct MeshTag;
using GeometryId = Id<GeometryTag>;
using MeshId = Id<MeshTag>;
struct Material {
    EntityId id{};
    std::string name{};
    double young_modulus_mpa{};
    std::optional<double> poisson_ratio{};
    std::optional<std::string> description{};
    bool operator==(const Material&) const = default;
};
struct Node {
    EntityId id{};
    std::array<double, 3> position{};
    std::optional<MeshId> mesh{};
    bool operator==(const Node&) const = default;
};
struct BeamSection {
    EntityId id{};
    std::string name{};
    EntityId material{};
    double area_mm2{};
    double i1_mm4{};
    double i2_mm4{};
    double torsion_mm4{};
    bool operator==(const BeamSection&) const = default;
};
struct Beam {
    EntityId id{};
    std::optional<EntityId> section{};
    std::array<EntityId, 2> nodes;
    std::array<double, 3> orientation{};
    std::optional<MeshId> mesh{};
    bool operator==(const Beam&) const = default;
};
void validate_record(const Beam&, const DocumentView&);
struct Part {
    EntityId id{};
    std::string name{};
    std::vector<EntityId> members{};
    bool operator==(const Part&) const = default;
};
struct Assembly {
    EntityId id{};
    std::string name{};
    std::vector<EntityId> children{};
    bool operator==(const Assembly&) const = default;
};
struct EntitySet {
    EntityId id{};
    std::string name{};
    std::vector<EntityId> members{};
    bool operator==(const EntitySet&) const = default;
};
struct IncludeDocument {
    EntityId id{};
    std::string path{};
    std::optional<EntityId> parent{};
    std::vector<EntityId> members{};
    bool operator==(const IncludeDocument&) const = default;
};
struct NodalForce {
    EntityId id{};
    EntityId node{};
    std::array<double, 3> force_n{};
    bool operator==(const NodalForce&) const = default;
};
struct Constraint {
    EntityId id{};
    std::vector<EntityId> nodes{};
    std::string dofs{};
    bool operator==(const Constraint&) const = default;
};
void validate_record(const Constraint&, const DocumentView&);
struct AnalysisDefinition {
    EntityId id{};
    std::string name{};
    TargetBinding target{};
    std::vector<EntityId> forces{};
    std::vector<EntityId> constraints{};
    std::optional<std::vector<EntityId>> load_cases{};
    bool operator==(const AnalysisDefinition&) const = default;
};
void validate_record(const AnalysisDefinition&, const DocumentView&);
struct SourceIdentifier {
    EntityId id{};
    EntityId entity{};
    std::string source_model_id{};
    EntityId include{};
    ProfileRef profile{};
    std::string name_space{};
    std::uint64_t number{};
    bool operator==(const SourceIdentifier&) const = default;
};
struct GeometryLine {
    GeometryId id{};
    std::array<double, 3> start{};
    std::array<double, 3> end{};
    std::uint64_t geometry_revision{};
    bool operator==(const GeometryLine&) const = default;
};
void validate_record(const GeometryLine&, const DocumentView&);
struct Mesh {
    MeshId id{};
    std::string name{};
    std::string origin{};
    std::optional<GeometryId> geometry{};
    std::uint64_t geometry_revision{};
    bool stale{};
    bool operator==(const Mesh&) const = default;
};
void validate_record(const Mesh&, const DocumentView&);
struct LoadCase {
    EntityId id{};
    std::string name{};
    std::vector<EntityId> forces{};
    std::vector<EntityId> constraints{};
    bool operator==(const LoadCase&) const = default;
};
struct Tri3 {
    EntityId id{};
    std::array<EntityId, 3> nodes;
    MeshId mesh{};
    bool operator==(const Tri3&) const = default;
};
void validate_record(const Tri3&, const DocumentView&);
void validate_relations(const DocumentView&);
} // namespace records

namespace records_detail {
inline void invalid(const char* message, const char* field) {
    throw RecordError(ErrorCode::invalid_input, message, field);
}
inline void check_text(std::string_view value, bool required, const char* field) {
    if ((required && value.empty()) || value.size() > 1024 ||
        std::any_of(
            value.begin(), value.end(), [](unsigned char ch) { return ch < 32 || ch == 127; }))
        invalid("Record text is missing, too long, or contains controls", field);
}
inline void check_profile(const ProfileRef& value, const char* field) {
    check_text(value.profile_id, true, field);
    check_text(value.profile_version, true, field);
    check_text(value.definition_digest, true, field);
}
template <class Range> void check_references(const Range& values, const char* field) {
    std::set<std::string_view> seen;
    for (const auto& value : values) {
        check_text(value.value, true, field);
        if (!seen.insert(value.value).second)
            invalid("Duplicate record reference", field);
    }
}
template <class Range> std::string pack_references(const Range& values) {
    std::vector<std::string> result;
    result.reserve(values.size());
    for (const auto& value : values)
        result.push_back(value.value);
    return record_wire::strings(result);
}
template <class Range> Range unpack_references(std::string_view bytes) {
    const auto values = record_wire::read_strings(bytes);
    Range result;
    if constexpr (requires { result.reserve(values.size()); }) {
        result.reserve(values.size());
        for (const auto& value : values)
            result.emplace_back(value);
    } else {
        if (result.size() != values.size())
            invalid("Wrong reference cardinality", "references");
        for (std::size_t index = 0; index < values.size(); ++index)
            result[index] = typename Range::value_type(values[index]);
    }
    return result;
}
template <class T> std::size_t dynamic_bytes(const T&) {
    return 0;
}
inline std::size_t dynamic_bytes(const std::string& value) {
    return value.size();
}
template <class Tag> std::size_t dynamic_bytes(const Id<Tag>& value) {
    return value.value.size();
}
inline std::size_t dynamic_bytes(const ProfileRef& value) {
    return value.profile_id.size() + value.profile_version.size() + value.definition_digest.size();
}
inline std::size_t dynamic_bytes(const TargetBinding& value) {
    return dynamic_bytes(value.profile) + value.analysis_kind.size();
}
template <class T> std::size_t dynamic_bytes(const std::optional<T>& value) {
    return value ? dynamic_bytes(*value) : 0;
}
template <class T, std::size_t N> std::size_t dynamic_bytes(const std::array<T, N>& values) {
    std::size_t result = 0;
    for (const auto& value : values)
        result += dynamic_bytes(value);
    return result;
}
template <class T> std::size_t dynamic_bytes(const std::vector<T>& values) {
    std::size_t result = values.size() * sizeof(T);
    for (const auto& value : values)
        result += dynamic_bytes(value);
    return result;
}
} // namespace records_detail

template <> struct RecordTraits<records::Material> {
    using Value = records::Material;
    static constexpr RecordTypeId type_id{4097};
    inline static const unsigned char token_value{};
    static const void* token() noexcept {
        return &token_value;
    }
    static const std::string& identity(const Value& value) noexcept {
        return value.id.value;
    }
    static void validate_fields(const Value& value) {
        records_detail::check_text(value.id.value, true, "id");
        records_detail::check_text(value.name, true, "name");
        if (!std::isfinite(value.young_modulus_mpa))
            records_detail::invalid("Number must be finite", "young_modulus_mpa");
        if (value.young_modulus_mpa <= 0)
            records_detail::invalid("Field is outside its allowed range", "young_modulus_mpa");
        if (value.poisson_ratio) {
            if (!std::isfinite(*value.poisson_ratio))
                records_detail::invalid("Number must be finite", "poisson_ratio");
            if (*value.poisson_ratio <= -1)
                records_detail::invalid("Field is outside its allowed range", "poisson_ratio");
            if (*value.poisson_ratio >= 0.5)
                records_detail::invalid("Field is outside its allowed range", "poisson_ratio");
        }
        if (value.description) {
            records_detail::check_text(*value.description, true, "description");
        }
    }
    static RecordDescriptor descriptor() {
        RecordDescriptor result;
        result.type = type_id;
        result.name = "Material";
        result.query_kind = "material";
        result.display_name = [](const void* object) -> std::string_view {
            return static_cast<const Value*>(object)->name;
        };
        result.current_version = 2;
        result.cpp_type_token = token();
        result.maximum_encoded_bytes = 4096;
        result.fields = {
            {RecordFieldId{2}, "name", RecordFieldKind::text, false, "", {}, 1},
            {RecordFieldId{3}, "young_modulus_mpa", RecordFieldKind::real, false, "MPa", {}, 1},
            {RecordFieldId{4}, "poisson_ratio", RecordFieldKind::real, true, "1", {}, 1},
            {RecordFieldId{5}, "description", RecordFieldKind::text, true, "", {}, 2},
        };
        result.encode = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            RecordInput input{{type_id, value.id.value}, 2, {}};
            input.fields.push_back(
                {RecordFieldId{2}, RecordFieldKind::text, "", record_wire::text(value.name)});
            input.fields.push_back({RecordFieldId{3},
                                    RecordFieldKind::real,
                                    "MPa",
                                    record_wire::real(value.young_modulus_mpa)});
            if (value.poisson_ratio) {
                input.fields.push_back({RecordFieldId{4},
                                        RecordFieldKind::real,
                                        "1",
                                        record_wire::real(*value.poisson_ratio)});
            }
            if (value.description) {
                input.fields.push_back({RecordFieldId{5},
                                        RecordFieldKind::text,
                                        "",
                                        record_wire::text(*value.description)});
            }
            return input;
        };
        result.decode = [](const RecordInput& input) -> std::shared_ptr<const void> {
            Value value;
            value.id = decltype(value.id)(input.key.identity);
            value.name =
                record_wire::read_text(record_wire::require(input, RecordFieldId{2}).payload);
            value.young_modulus_mpa =
                record_wire::read_real(record_wire::require(input, RecordFieldId{3}).payload);
            if (const auto* field = record_wire::find(input, RecordFieldId{4})) {
                value.poisson_ratio = record_wire::read_real(field->payload);
            }
            if (const auto* field = record_wire::find(input, RecordFieldId{5})) {
                value.description = record_wire::read_text(field->payload);
            }
            validate_fields(value);
            return std::make_shared<const Value>(std::move(value));
        };
        result.owned_bytes = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            return sizeof(Value) + records_detail::dynamic_bytes(value.id) +
                   records_detail::dynamic_bytes(value.name) +
                   records_detail::dynamic_bytes(value.young_modulus_mpa) +
                   records_detail::dynamic_bytes(value.poisson_ratio) +
                   records_detail::dynamic_bytes(value.description);
        };
        result.references = [](const void* object, const RecordReferenceVisitor& visitor) {
            (void)object;
            (void)visitor;
        };
        result.validate = [](const void* object, const DocumentView& view) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            (void)view;
        };
        return result;
    }
};
template <> struct RecordTraits<records::Node> {
    using Value = records::Node;
    static constexpr RecordTypeId type_id{4098};
    inline static const unsigned char token_value{};
    static const void* token() noexcept {
        return &token_value;
    }
    static const std::string& identity(const Value& value) noexcept {
        return value.id.value;
    }
    static void validate_fields(const Value& value) {
        records_detail::check_text(value.id.value, true, "id");
        for (double part : value.position)
            if (!std::isfinite(part))
                records_detail::invalid("Vector must be finite", "position");
        if (value.mesh) {
            records_detail::check_text((*value.mesh).value, true, "mesh");
        }
    }
    static RecordDescriptor descriptor() {
        RecordDescriptor result;
        result.type = type_id;
        result.name = "Node";
        result.query_kind = "node";
        result.display_name = [](const void*) -> std::string_view { return {}; };
        result.current_version = 1;
        result.cpp_type_token = token();
        result.maximum_encoded_bytes = 256;
        result.fields = {
            {RecordFieldId{2}, "position", RecordFieldKind::vector3, false, "mm", {}, 1},
            {RecordFieldId{3},
             "mesh",
             RecordFieldKind::reference,
             true,
             "",
             {RecordTypeId{4110}},
             1},
        };
        result.encode = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            RecordInput input{{type_id, value.id.value}, 1, {}};
            input.fields.push_back({RecordFieldId{2},
                                    RecordFieldKind::vector3,
                                    "mm",
                                    record_wire::vector3(value.position)});
            if (value.mesh) {
                input.fields.push_back({RecordFieldId{3},
                                        RecordFieldKind::reference,
                                        "",
                                        record_wire::text((*value.mesh).value)});
            }
            return input;
        };
        result.decode = [](const RecordInput& input) -> std::shared_ptr<const void> {
            Value value;
            value.id = decltype(value.id)(input.key.identity);
            value.position =
                record_wire::read_vector3(record_wire::require(input, RecordFieldId{2}).payload);
            if (const auto* field = record_wire::find(input, RecordFieldId{3})) {
                value.mesh = records::MeshId(record_wire::read_text(field->payload));
            }
            validate_fields(value);
            return std::make_shared<const Value>(std::move(value));
        };
        result.owned_bytes = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            return sizeof(Value) + records_detail::dynamic_bytes(value.id) +
                   records_detail::dynamic_bytes(value.position) +
                   records_detail::dynamic_bytes(value.mesh);
        };
        result.references = [](const void* object, const RecordReferenceVisitor& visitor) {
            const auto& value = *static_cast<const Value*>(object);
            static constexpr std::array targets_3{RecordTypeId{4110}};
            if (value.mesh)
                visitor(RecordFieldId{3}, value.mesh->value, targets_3);
        };
        result.validate = [](const void* object, const DocumentView& view) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            (void)view;
        };
        return result;
    }
};
template <> struct RecordTraits<records::BeamSection> {
    using Value = records::BeamSection;
    static constexpr RecordTypeId type_id{4099};
    inline static const unsigned char token_value{};
    static const void* token() noexcept {
        return &token_value;
    }
    static const std::string& identity(const Value& value) noexcept {
        return value.id.value;
    }
    static void validate_fields(const Value& value) {
        records_detail::check_text(value.id.value, true, "id");
        records_detail::check_text(value.name, true, "name");
        records_detail::check_text((value.material).value, true, "material");
        if (!std::isfinite(value.area_mm2))
            records_detail::invalid("Number must be finite", "area_mm2");
        if (value.area_mm2 <= 0)
            records_detail::invalid("Field is outside its allowed range", "area_mm2");
        if (!std::isfinite(value.i1_mm4))
            records_detail::invalid("Number must be finite", "i1_mm4");
        if (value.i1_mm4 <= 0)
            records_detail::invalid("Field is outside its allowed range", "i1_mm4");
        if (!std::isfinite(value.i2_mm4))
            records_detail::invalid("Number must be finite", "i2_mm4");
        if (value.i2_mm4 <= 0)
            records_detail::invalid("Field is outside its allowed range", "i2_mm4");
        if (!std::isfinite(value.torsion_mm4))
            records_detail::invalid("Number must be finite", "torsion_mm4");
        if (value.torsion_mm4 <= 0)
            records_detail::invalid("Field is outside its allowed range", "torsion_mm4");
    }
    static RecordDescriptor descriptor() {
        RecordDescriptor result;
        result.type = type_id;
        result.name = "BeamSection";
        result.query_kind = "section";
        result.display_name = [](const void* object) -> std::string_view {
            return static_cast<const Value*>(object)->name;
        };
        result.current_version = 1;
        result.cpp_type_token = token();
        result.maximum_encoded_bytes = 16777216;
        result.fields = {
            {RecordFieldId{2}, "name", RecordFieldKind::text, false, "", {}, 1},
            {RecordFieldId{3},
             "material",
             RecordFieldKind::reference,
             false,
             "",
             {RecordTypeId{4097}},
             1},
            {RecordFieldId{4}, "area_mm2", RecordFieldKind::real, false, "mm2", {}, 1},
            {RecordFieldId{5}, "i1_mm4", RecordFieldKind::real, false, "mm4", {}, 1},
            {RecordFieldId{6}, "i2_mm4", RecordFieldKind::real, false, "mm4", {}, 1},
            {RecordFieldId{7}, "torsion_mm4", RecordFieldKind::real, false, "mm4", {}, 1},
        };
        result.encode = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            RecordInput input{{type_id, value.id.value}, 1, {}};
            input.fields.push_back(
                {RecordFieldId{2}, RecordFieldKind::text, "", record_wire::text(value.name)});
            input.fields.push_back({RecordFieldId{3},
                                    RecordFieldKind::reference,
                                    "",
                                    record_wire::text((value.material).value)});
            input.fields.push_back({RecordFieldId{4},
                                    RecordFieldKind::real,
                                    "mm2",
                                    record_wire::real(value.area_mm2)});
            input.fields.push_back(
                {RecordFieldId{5}, RecordFieldKind::real, "mm4", record_wire::real(value.i1_mm4)});
            input.fields.push_back(
                {RecordFieldId{6}, RecordFieldKind::real, "mm4", record_wire::real(value.i2_mm4)});
            input.fields.push_back({RecordFieldId{7},
                                    RecordFieldKind::real,
                                    "mm4",
                                    record_wire::real(value.torsion_mm4)});
            return input;
        };
        result.decode = [](const RecordInput& input) -> std::shared_ptr<const void> {
            Value value;
            value.id = decltype(value.id)(input.key.identity);
            value.name =
                record_wire::read_text(record_wire::require(input, RecordFieldId{2}).payload);
            value.material = EntityId(
                record_wire::read_text(record_wire::require(input, RecordFieldId{3}).payload));
            value.area_mm2 =
                record_wire::read_real(record_wire::require(input, RecordFieldId{4}).payload);
            value.i1_mm4 =
                record_wire::read_real(record_wire::require(input, RecordFieldId{5}).payload);
            value.i2_mm4 =
                record_wire::read_real(record_wire::require(input, RecordFieldId{6}).payload);
            value.torsion_mm4 =
                record_wire::read_real(record_wire::require(input, RecordFieldId{7}).payload);
            validate_fields(value);
            return std::make_shared<const Value>(std::move(value));
        };
        result.owned_bytes = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            return sizeof(Value) + records_detail::dynamic_bytes(value.id) +
                   records_detail::dynamic_bytes(value.name) +
                   records_detail::dynamic_bytes(value.material) +
                   records_detail::dynamic_bytes(value.area_mm2) +
                   records_detail::dynamic_bytes(value.i1_mm4) +
                   records_detail::dynamic_bytes(value.i2_mm4) +
                   records_detail::dynamic_bytes(value.torsion_mm4);
        };
        result.references = [](const void* object, const RecordReferenceVisitor& visitor) {
            const auto& value = *static_cast<const Value*>(object);
            static constexpr std::array targets_3{RecordTypeId{4097}};
            visitor(RecordFieldId{3}, value.material.value, targets_3);
        };
        result.validate = [](const void* object, const DocumentView& view) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            (void)view;
        };
        return result;
    }
};
template <> struct RecordTraits<records::Beam> {
    using Value = records::Beam;
    static constexpr RecordTypeId type_id{4100};
    inline static const unsigned char token_value{};
    static const void* token() noexcept {
        return &token_value;
    }
    static const std::string& identity(const Value& value) noexcept {
        return value.id.value;
    }
    static void validate_fields(const Value& value) {
        records_detail::check_text(value.id.value, true, "id");
        if (value.section) {
            records_detail::check_text((*value.section).value, true, "section");
        }
        records_detail::check_references(value.nodes, "nodes");
        for (double part : value.orientation)
            if (!std::isfinite(part))
                records_detail::invalid("Vector must be finite", "orientation");
        if (value.mesh) {
            records_detail::check_text((*value.mesh).value, true, "mesh");
        }
    }
    static RecordDescriptor descriptor() {
        RecordDescriptor result;
        result.type = type_id;
        result.name = "Beam";
        result.query_kind = "beam";
        result.display_name = [](const void*) -> std::string_view { return {}; };
        result.current_version = 1;
        result.cpp_type_token = token();
        result.maximum_encoded_bytes = 16777216;
        result.fields = {
            {RecordFieldId{2},
             "section",
             RecordFieldKind::reference,
             true,
             "",
             {RecordTypeId{4099}},
             1},
            {RecordFieldId{3},
             "nodes",
             RecordFieldKind::references,
             false,
             "",
             {RecordTypeId{4098}},
             1},
            {RecordFieldId{4}, "orientation", RecordFieldKind::vector3, false, "1", {}, 1},
            {RecordFieldId{5},
             "mesh",
             RecordFieldKind::reference,
             true,
             "",
             {RecordTypeId{4110}},
             1},
        };
        result.encode = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            RecordInput input{{type_id, value.id.value}, 1, {}};
            if (value.section) {
                input.fields.push_back({RecordFieldId{2},
                                        RecordFieldKind::reference,
                                        "",
                                        record_wire::text((*value.section).value)});
            }
            input.fields.push_back({RecordFieldId{3},
                                    RecordFieldKind::references,
                                    "",
                                    records_detail::pack_references(value.nodes)});
            input.fields.push_back({RecordFieldId{4},
                                    RecordFieldKind::vector3,
                                    "1",
                                    record_wire::vector3(value.orientation)});
            if (value.mesh) {
                input.fields.push_back({RecordFieldId{5},
                                        RecordFieldKind::reference,
                                        "",
                                        record_wire::text((*value.mesh).value)});
            }
            return input;
        };
        result.decode = [](const RecordInput& input) -> std::shared_ptr<const void> {
            Value value;
            value.id = decltype(value.id)(input.key.identity);
            if (const auto* field = record_wire::find(input, RecordFieldId{2})) {
                value.section = EntityId(record_wire::read_text(field->payload));
            }
            value.nodes = records_detail::unpack_references<std::array<EntityId, 2>>(
                record_wire::require(input, RecordFieldId{3}).payload);
            value.orientation =
                record_wire::read_vector3(record_wire::require(input, RecordFieldId{4}).payload);
            if (const auto* field = record_wire::find(input, RecordFieldId{5})) {
                value.mesh = records::MeshId(record_wire::read_text(field->payload));
            }
            validate_fields(value);
            return std::make_shared<const Value>(std::move(value));
        };
        result.owned_bytes = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            return sizeof(Value) + records_detail::dynamic_bytes(value.id) +
                   records_detail::dynamic_bytes(value.section) +
                   records_detail::dynamic_bytes(value.nodes) +
                   records_detail::dynamic_bytes(value.orientation) +
                   records_detail::dynamic_bytes(value.mesh);
        };
        result.references = [](const void* object, const RecordReferenceVisitor& visitor) {
            const auto& value = *static_cast<const Value*>(object);
            static constexpr std::array targets_2{RecordTypeId{4099}};
            if (value.section)
                visitor(RecordFieldId{2}, value.section->value, targets_2);
            static constexpr std::array targets_3{RecordTypeId{4098}};
            for (const auto& item : value.nodes)
                visitor(RecordFieldId{3}, item.value, targets_3);
            static constexpr std::array targets_5{RecordTypeId{4110}};
            if (value.mesh)
                visitor(RecordFieldId{5}, value.mesh->value, targets_5);
        };
        result.validate = [](const void* object, const DocumentView& view) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            records::validate_record(value, view);
        };
        return result;
    }
};
template <> struct RecordTraits<records::Part> {
    using Value = records::Part;
    static constexpr RecordTypeId type_id{4101};
    inline static const unsigned char token_value{};
    static const void* token() noexcept {
        return &token_value;
    }
    static const std::string& identity(const Value& value) noexcept {
        return value.id.value;
    }
    static void validate_fields(const Value& value) {
        records_detail::check_text(value.id.value, true, "id");
        records_detail::check_text(value.name, false, "name");
        records_detail::check_references(value.members, "members");
    }
    static RecordDescriptor descriptor() {
        RecordDescriptor result;
        result.type = type_id;
        result.name = "Part";
        result.query_kind = "part";
        result.display_name = [](const void* object) -> std::string_view {
            return static_cast<const Value*>(object)->name;
        };
        result.current_version = 1;
        result.cpp_type_token = token();
        result.maximum_encoded_bytes = 16777216;
        result.fields = {
            {RecordFieldId{2}, "name", RecordFieldKind::text, false, "", {}, 1},
            {RecordFieldId{3},
             "members",
             RecordFieldKind::references,
             false,
             "",
             {RecordTypeId{4098}, RecordTypeId{4100}},
             1},
        };
        result.encode = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            RecordInput input{{type_id, value.id.value}, 1, {}};
            input.fields.push_back(
                {RecordFieldId{2}, RecordFieldKind::text, "", record_wire::text(value.name)});
            input.fields.push_back({RecordFieldId{3},
                                    RecordFieldKind::references,
                                    "",
                                    records_detail::pack_references(value.members)});
            return input;
        };
        result.decode = [](const RecordInput& input) -> std::shared_ptr<const void> {
            Value value;
            value.id = decltype(value.id)(input.key.identity);
            value.name =
                record_wire::read_text(record_wire::require(input, RecordFieldId{2}).payload);
            value.members = records_detail::unpack_references<std::vector<EntityId>>(
                record_wire::require(input, RecordFieldId{3}).payload);
            validate_fields(value);
            return std::make_shared<const Value>(std::move(value));
        };
        result.owned_bytes = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            return sizeof(Value) + records_detail::dynamic_bytes(value.id) +
                   records_detail::dynamic_bytes(value.name) +
                   records_detail::dynamic_bytes(value.members);
        };
        result.references = [](const void* object, const RecordReferenceVisitor& visitor) {
            const auto& value = *static_cast<const Value*>(object);
            static constexpr std::array targets_3{RecordTypeId{4098}, RecordTypeId{4100}};
            for (const auto& item : value.members)
                visitor(RecordFieldId{3}, item.value, targets_3);
        };
        result.validate = [](const void* object, const DocumentView& view) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            (void)view;
        };
        return result;
    }
};
template <> struct RecordTraits<records::Assembly> {
    using Value = records::Assembly;
    static constexpr RecordTypeId type_id{4102};
    inline static const unsigned char token_value{};
    static const void* token() noexcept {
        return &token_value;
    }
    static const std::string& identity(const Value& value) noexcept {
        return value.id.value;
    }
    static void validate_fields(const Value& value) {
        records_detail::check_text(value.id.value, true, "id");
        records_detail::check_text(value.name, false, "name");
        records_detail::check_references(value.children, "children");
    }
    static RecordDescriptor descriptor() {
        RecordDescriptor result;
        result.type = type_id;
        result.name = "Assembly";
        result.query_kind = "assembly";
        result.display_name = [](const void* object) -> std::string_view {
            return static_cast<const Value*>(object)->name;
        };
        result.current_version = 1;
        result.cpp_type_token = token();
        result.maximum_encoded_bytes = 16777216;
        result.fields = {
            {RecordFieldId{2}, "name", RecordFieldKind::text, false, "", {}, 1},
            {RecordFieldId{3},
             "children",
             RecordFieldKind::references,
             false,
             "",
             {RecordTypeId{4101}, RecordTypeId{4102}},
             1},
        };
        result.encode = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            RecordInput input{{type_id, value.id.value}, 1, {}};
            input.fields.push_back(
                {RecordFieldId{2}, RecordFieldKind::text, "", record_wire::text(value.name)});
            input.fields.push_back({RecordFieldId{3},
                                    RecordFieldKind::references,
                                    "",
                                    records_detail::pack_references(value.children)});
            return input;
        };
        result.decode = [](const RecordInput& input) -> std::shared_ptr<const void> {
            Value value;
            value.id = decltype(value.id)(input.key.identity);
            value.name =
                record_wire::read_text(record_wire::require(input, RecordFieldId{2}).payload);
            value.children = records_detail::unpack_references<std::vector<EntityId>>(
                record_wire::require(input, RecordFieldId{3}).payload);
            validate_fields(value);
            return std::make_shared<const Value>(std::move(value));
        };
        result.owned_bytes = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            return sizeof(Value) + records_detail::dynamic_bytes(value.id) +
                   records_detail::dynamic_bytes(value.name) +
                   records_detail::dynamic_bytes(value.children);
        };
        result.references = [](const void* object, const RecordReferenceVisitor& visitor) {
            const auto& value = *static_cast<const Value*>(object);
            static constexpr std::array targets_3{RecordTypeId{4101}, RecordTypeId{4102}};
            for (const auto& item : value.children)
                visitor(RecordFieldId{3}, item.value, targets_3);
        };
        result.validate = [](const void* object, const DocumentView& view) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            (void)view;
        };
        return result;
    }
};
template <> struct RecordTraits<records::EntitySet> {
    using Value = records::EntitySet;
    static constexpr RecordTypeId type_id{4103};
    inline static const unsigned char token_value{};
    static const void* token() noexcept {
        return &token_value;
    }
    static const std::string& identity(const Value& value) noexcept {
        return value.id.value;
    }
    static void validate_fields(const Value& value) {
        records_detail::check_text(value.id.value, true, "id");
        records_detail::check_text(value.name, false, "name");
        records_detail::check_references(value.members, "members");
    }
    static RecordDescriptor descriptor() {
        RecordDescriptor result;
        result.type = type_id;
        result.name = "EntitySet";
        result.query_kind = "set";
        result.display_name = [](const void* object) -> std::string_view {
            return static_cast<const Value*>(object)->name;
        };
        result.current_version = 1;
        result.cpp_type_token = token();
        result.maximum_encoded_bytes = 16777216;
        result.fields = {
            {RecordFieldId{2}, "name", RecordFieldKind::text, false, "", {}, 1},
            {RecordFieldId{3},
             "members",
             RecordFieldKind::references,
             false,
             "",
             {RecordTypeId{4098}, RecordTypeId{4100}},
             1},
        };
        result.encode = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            RecordInput input{{type_id, value.id.value}, 1, {}};
            input.fields.push_back(
                {RecordFieldId{2}, RecordFieldKind::text, "", record_wire::text(value.name)});
            input.fields.push_back({RecordFieldId{3},
                                    RecordFieldKind::references,
                                    "",
                                    records_detail::pack_references(value.members)});
            return input;
        };
        result.decode = [](const RecordInput& input) -> std::shared_ptr<const void> {
            Value value;
            value.id = decltype(value.id)(input.key.identity);
            value.name =
                record_wire::read_text(record_wire::require(input, RecordFieldId{2}).payload);
            value.members = records_detail::unpack_references<std::vector<EntityId>>(
                record_wire::require(input, RecordFieldId{3}).payload);
            validate_fields(value);
            return std::make_shared<const Value>(std::move(value));
        };
        result.owned_bytes = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            return sizeof(Value) + records_detail::dynamic_bytes(value.id) +
                   records_detail::dynamic_bytes(value.name) +
                   records_detail::dynamic_bytes(value.members);
        };
        result.references = [](const void* object, const RecordReferenceVisitor& visitor) {
            const auto& value = *static_cast<const Value*>(object);
            static constexpr std::array targets_3{RecordTypeId{4098}, RecordTypeId{4100}};
            for (const auto& item : value.members)
                visitor(RecordFieldId{3}, item.value, targets_3);
        };
        result.validate = [](const void* object, const DocumentView& view) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            (void)view;
        };
        return result;
    }
};
template <> struct RecordTraits<records::IncludeDocument> {
    using Value = records::IncludeDocument;
    static constexpr RecordTypeId type_id{4104};
    inline static const unsigned char token_value{};
    static const void* token() noexcept {
        return &token_value;
    }
    static const std::string& identity(const Value& value) noexcept {
        return value.id.value;
    }
    static void validate_fields(const Value& value) {
        records_detail::check_text(value.id.value, true, "id");
        records_detail::check_text(value.path, true, "path");
        if (value.parent) {
            records_detail::check_text((*value.parent).value, true, "parent");
        }
        records_detail::check_references(value.members, "members");
    }
    static RecordDescriptor descriptor() {
        RecordDescriptor result;
        result.type = type_id;
        result.name = "IncludeDocument";
        result.query_kind = "include";
        result.display_name = [](const void* object) -> std::string_view {
            return static_cast<const Value*>(object)->path;
        };
        result.current_version = 1;
        result.cpp_type_token = token();
        result.maximum_encoded_bytes = 16777216;
        result.fields = {
            {RecordFieldId{2}, "path", RecordFieldKind::text, false, "", {}, 1},
            {RecordFieldId{3},
             "parent",
             RecordFieldKind::reference,
             true,
             "",
             {RecordTypeId{4104}},
             1},
            {RecordFieldId{4},
             "members",
             RecordFieldKind::references,
             false,
             "",
             {RecordTypeId{4097},
              RecordTypeId{4098},
              RecordTypeId{4099},
              RecordTypeId{4100},
              RecordTypeId{4101},
              RecordTypeId{4102},
              RecordTypeId{4103},
              RecordTypeId{4105},
              RecordTypeId{4106},
              RecordTypeId{4107},
              RecordTypeId{4111}},
             1},
        };
        result.encode = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            RecordInput input{{type_id, value.id.value}, 1, {}};
            input.fields.push_back(
                {RecordFieldId{2}, RecordFieldKind::text, "", record_wire::text(value.path)});
            if (value.parent) {
                input.fields.push_back({RecordFieldId{3},
                                        RecordFieldKind::reference,
                                        "",
                                        record_wire::text((*value.parent).value)});
            }
            input.fields.push_back({RecordFieldId{4},
                                    RecordFieldKind::references,
                                    "",
                                    records_detail::pack_references(value.members)});
            return input;
        };
        result.decode = [](const RecordInput& input) -> std::shared_ptr<const void> {
            Value value;
            value.id = decltype(value.id)(input.key.identity);
            value.path =
                record_wire::read_text(record_wire::require(input, RecordFieldId{2}).payload);
            if (const auto* field = record_wire::find(input, RecordFieldId{3})) {
                value.parent = EntityId(record_wire::read_text(field->payload));
            }
            value.members = records_detail::unpack_references<std::vector<EntityId>>(
                record_wire::require(input, RecordFieldId{4}).payload);
            validate_fields(value);
            return std::make_shared<const Value>(std::move(value));
        };
        result.owned_bytes = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            return sizeof(Value) + records_detail::dynamic_bytes(value.id) +
                   records_detail::dynamic_bytes(value.path) +
                   records_detail::dynamic_bytes(value.parent) +
                   records_detail::dynamic_bytes(value.members);
        };
        result.references = [](const void* object, const RecordReferenceVisitor& visitor) {
            const auto& value = *static_cast<const Value*>(object);
            static constexpr std::array targets_3{RecordTypeId{4104}};
            if (value.parent)
                visitor(RecordFieldId{3}, value.parent->value, targets_3);
            static constexpr std::array targets_4{RecordTypeId{4097},
                                                  RecordTypeId{4098},
                                                  RecordTypeId{4099},
                                                  RecordTypeId{4100},
                                                  RecordTypeId{4101},
                                                  RecordTypeId{4102},
                                                  RecordTypeId{4103},
                                                  RecordTypeId{4105},
                                                  RecordTypeId{4106},
                                                  RecordTypeId{4107},
                                                  RecordTypeId{4111}};
            for (const auto& item : value.members)
                visitor(RecordFieldId{4}, item.value, targets_4);
        };
        result.validate = [](const void* object, const DocumentView& view) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            (void)view;
        };
        return result;
    }
};
template <> struct RecordTraits<records::NodalForce> {
    using Value = records::NodalForce;
    static constexpr RecordTypeId type_id{4105};
    inline static const unsigned char token_value{};
    static const void* token() noexcept {
        return &token_value;
    }
    static const std::string& identity(const Value& value) noexcept {
        return value.id.value;
    }
    static void validate_fields(const Value& value) {
        records_detail::check_text(value.id.value, true, "id");
        records_detail::check_text((value.node).value, true, "node");
        for (double part : value.force_n)
            if (!std::isfinite(part))
                records_detail::invalid("Vector must be finite", "force_n");
    }
    static RecordDescriptor descriptor() {
        RecordDescriptor result;
        result.type = type_id;
        result.name = "NodalForce";
        result.query_kind = "force";
        result.display_name = [](const void*) -> std::string_view { return {}; };
        result.current_version = 1;
        result.cpp_type_token = token();
        result.maximum_encoded_bytes = 16777216;
        result.fields = {
            {RecordFieldId{2},
             "node",
             RecordFieldKind::reference,
             false,
             "",
             {RecordTypeId{4098}},
             1},
            {RecordFieldId{3}, "force_n", RecordFieldKind::vector3, false, "N", {}, 1},
        };
        result.encode = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            RecordInput input{{type_id, value.id.value}, 1, {}};
            input.fields.push_back({RecordFieldId{2},
                                    RecordFieldKind::reference,
                                    "",
                                    record_wire::text((value.node).value)});
            input.fields.push_back({RecordFieldId{3},
                                    RecordFieldKind::vector3,
                                    "N",
                                    record_wire::vector3(value.force_n)});
            return input;
        };
        result.decode = [](const RecordInput& input) -> std::shared_ptr<const void> {
            Value value;
            value.id = decltype(value.id)(input.key.identity);
            value.node = EntityId(
                record_wire::read_text(record_wire::require(input, RecordFieldId{2}).payload));
            value.force_n =
                record_wire::read_vector3(record_wire::require(input, RecordFieldId{3}).payload);
            validate_fields(value);
            return std::make_shared<const Value>(std::move(value));
        };
        result.owned_bytes = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            return sizeof(Value) + records_detail::dynamic_bytes(value.id) +
                   records_detail::dynamic_bytes(value.node) +
                   records_detail::dynamic_bytes(value.force_n);
        };
        result.references = [](const void* object, const RecordReferenceVisitor& visitor) {
            const auto& value = *static_cast<const Value*>(object);
            static constexpr std::array targets_2{RecordTypeId{4098}};
            visitor(RecordFieldId{2}, value.node.value, targets_2);
        };
        result.validate = [](const void* object, const DocumentView& view) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            (void)view;
        };
        return result;
    }
};
template <> struct RecordTraits<records::Constraint> {
    using Value = records::Constraint;
    static constexpr RecordTypeId type_id{4106};
    inline static const unsigned char token_value{};
    static const void* token() noexcept {
        return &token_value;
    }
    static const std::string& identity(const Value& value) noexcept {
        return value.id.value;
    }
    static void validate_fields(const Value& value) {
        records_detail::check_text(value.id.value, true, "id");
        records_detail::check_references(value.nodes, "nodes");
        if ((value.nodes).empty())
            records_detail::invalid("References are required", "nodes");
        records_detail::check_text(value.dofs, true, "dofs");
    }
    static RecordDescriptor descriptor() {
        RecordDescriptor result;
        result.type = type_id;
        result.name = "Constraint";
        result.query_kind = "constraint";
        result.display_name = [](const void*) -> std::string_view { return {}; };
        result.current_version = 1;
        result.cpp_type_token = token();
        result.maximum_encoded_bytes = 16777216;
        result.fields = {
            {RecordFieldId{2},
             "nodes",
             RecordFieldKind::references,
             false,
             "",
             {RecordTypeId{4098}},
             1},
            {RecordFieldId{3}, "dofs", RecordFieldKind::text, false, "", {}, 1},
        };
        result.encode = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            RecordInput input{{type_id, value.id.value}, 1, {}};
            input.fields.push_back({RecordFieldId{2},
                                    RecordFieldKind::references,
                                    "",
                                    records_detail::pack_references(value.nodes)});
            input.fields.push_back(
                {RecordFieldId{3}, RecordFieldKind::text, "", record_wire::text(value.dofs)});
            return input;
        };
        result.decode = [](const RecordInput& input) -> std::shared_ptr<const void> {
            Value value;
            value.id = decltype(value.id)(input.key.identity);
            value.nodes = records_detail::unpack_references<std::vector<EntityId>>(
                record_wire::require(input, RecordFieldId{2}).payload);
            value.dofs =
                record_wire::read_text(record_wire::require(input, RecordFieldId{3}).payload);
            validate_fields(value);
            return std::make_shared<const Value>(std::move(value));
        };
        result.owned_bytes = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            return sizeof(Value) + records_detail::dynamic_bytes(value.id) +
                   records_detail::dynamic_bytes(value.nodes) +
                   records_detail::dynamic_bytes(value.dofs);
        };
        result.references = [](const void* object, const RecordReferenceVisitor& visitor) {
            const auto& value = *static_cast<const Value*>(object);
            static constexpr std::array targets_2{RecordTypeId{4098}};
            for (const auto& item : value.nodes)
                visitor(RecordFieldId{2}, item.value, targets_2);
        };
        result.validate = [](const void* object, const DocumentView& view) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            records::validate_record(value, view);
        };
        return result;
    }
};
template <> struct RecordTraits<records::AnalysisDefinition> {
    using Value = records::AnalysisDefinition;
    static constexpr RecordTypeId type_id{4107};
    inline static const unsigned char token_value{};
    static const void* token() noexcept {
        return &token_value;
    }
    static const std::string& identity(const Value& value) noexcept {
        return value.id.value;
    }
    static void validate_fields(const Value& value) {
        records_detail::check_text(value.id.value, true, "id");
        records_detail::check_text(value.name, true, "name");
        records_detail::check_profile((value.target).profile, "target");
        records_detail::check_text((value.target).analysis_kind, true, "target");
        records_detail::check_references(value.forces, "forces");
        records_detail::check_references(value.constraints, "constraints");
        if (value.load_cases) {
            records_detail::check_references(*value.load_cases, "load_cases");
        }
    }
    static RecordDescriptor descriptor() {
        RecordDescriptor result;
        result.type = type_id;
        result.name = "AnalysisDefinition";
        result.query_kind = "analysis";
        result.display_name = [](const void* object) -> std::string_view {
            return static_cast<const Value*>(object)->name;
        };
        result.current_version = 2;
        result.cpp_type_token = token();
        result.maximum_encoded_bytes = 16777216;
        result.fields = {
            {RecordFieldId{2}, "name", RecordFieldKind::text, false, "", {}, 1},
            {RecordFieldId{3}, "target", RecordFieldKind::target, false, "", {}, 1},
            {RecordFieldId{4},
             "forces",
             RecordFieldKind::references,
             false,
             "",
             {RecordTypeId{4105}},
             1},
            {RecordFieldId{5},
             "constraints",
             RecordFieldKind::references,
             false,
             "",
             {RecordTypeId{4106}},
             1},
            {RecordFieldId{6},
             "load_cases",
             RecordFieldKind::references,
             true,
             "",
             {RecordTypeId{4111}},
             2},
        };
        result.encode = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            RecordInput input{{type_id, value.id.value}, 2, {}};
            input.fields.push_back(
                {RecordFieldId{2}, RecordFieldKind::text, "", record_wire::text(value.name)});
            input.fields.push_back(
                {RecordFieldId{3}, RecordFieldKind::target, "", record_wire::target(value.target)});
            input.fields.push_back({RecordFieldId{4},
                                    RecordFieldKind::references,
                                    "",
                                    records_detail::pack_references(value.forces)});
            input.fields.push_back({RecordFieldId{5},
                                    RecordFieldKind::references,
                                    "",
                                    records_detail::pack_references(value.constraints)});
            if (value.load_cases) {
                input.fields.push_back({RecordFieldId{6},
                                        RecordFieldKind::references,
                                        "",
                                        records_detail::pack_references(*value.load_cases)});
            }
            return input;
        };
        result.decode = [](const RecordInput& input) -> std::shared_ptr<const void> {
            Value value;
            value.id = decltype(value.id)(input.key.identity);
            value.name =
                record_wire::read_text(record_wire::require(input, RecordFieldId{2}).payload);
            value.target =
                record_wire::read_target(record_wire::require(input, RecordFieldId{3}).payload);
            value.forces = records_detail::unpack_references<std::vector<EntityId>>(
                record_wire::require(input, RecordFieldId{4}).payload);
            value.constraints = records_detail::unpack_references<std::vector<EntityId>>(
                record_wire::require(input, RecordFieldId{5}).payload);
            if (const auto* field = record_wire::find(input, RecordFieldId{6})) {
                value.load_cases =
                    records_detail::unpack_references<std::vector<EntityId>>(field->payload);
            }
            validate_fields(value);
            return std::make_shared<const Value>(std::move(value));
        };
        result.owned_bytes = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            return sizeof(Value) + records_detail::dynamic_bytes(value.id) +
                   records_detail::dynamic_bytes(value.name) +
                   records_detail::dynamic_bytes(value.target) +
                   records_detail::dynamic_bytes(value.forces) +
                   records_detail::dynamic_bytes(value.constraints) +
                   records_detail::dynamic_bytes(value.load_cases);
        };
        result.references = [](const void* object, const RecordReferenceVisitor& visitor) {
            const auto& value = *static_cast<const Value*>(object);
            static constexpr std::array targets_4{RecordTypeId{4105}};
            for (const auto& item : value.forces)
                visitor(RecordFieldId{4}, item.value, targets_4);
            static constexpr std::array targets_5{RecordTypeId{4106}};
            for (const auto& item : value.constraints)
                visitor(RecordFieldId{5}, item.value, targets_5);
            static constexpr std::array targets_6{RecordTypeId{4111}};
            if (value.load_cases) {
                for (const auto& item : *value.load_cases)
                    visitor(RecordFieldId{6}, item.value, targets_6);
            }
        };
        result.validate = [](const void* object, const DocumentView& view) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            records::validate_record(value, view);
        };
        return result;
    }
};
template <> struct RecordTraits<records::SourceIdentifier> {
    using Value = records::SourceIdentifier;
    static constexpr RecordTypeId type_id{4108};
    inline static const unsigned char token_value{};
    static const void* token() noexcept {
        return &token_value;
    }
    static const std::string& identity(const Value& value) noexcept {
        return value.id.value;
    }
    static void validate_fields(const Value& value) {
        records_detail::check_text(value.id.value, true, "id");
        records_detail::check_text((value.entity).value, true, "entity");
        records_detail::check_text(value.source_model_id, true, "source_model_id");
        records_detail::check_text((value.include).value, true, "include");
        records_detail::check_profile(value.profile, "profile");
        records_detail::check_text(value.name_space, true, "name_space");
        if (value.number < 1)
            records_detail::invalid("Field is outside its allowed range", "number");
    }
    static RecordDescriptor descriptor() {
        RecordDescriptor result;
        result.type = type_id;
        result.name = "SourceIdentifier";
        result.query_kind = "";
        result.display_name = [](const void*) -> std::string_view { return {}; };
        result.current_version = 1;
        result.cpp_type_token = token();
        result.maximum_encoded_bytes = 16777216;
        result.fields = {
            {RecordFieldId{2},
             "entity",
             RecordFieldKind::reference,
             false,
             "",
             {RecordTypeId{4097},
              RecordTypeId{4098},
              RecordTypeId{4099},
              RecordTypeId{4100},
              RecordTypeId{4101},
              RecordTypeId{4102},
              RecordTypeId{4103},
              RecordTypeId{4105},
              RecordTypeId{4106},
              RecordTypeId{4107},
              RecordTypeId{4111}},
             1},
            {RecordFieldId{3}, "source_model_id", RecordFieldKind::text, false, "", {}, 1},
            {RecordFieldId{4},
             "include",
             RecordFieldKind::reference,
             false,
             "",
             {RecordTypeId{4104}},
             1},
            {RecordFieldId{5}, "profile", RecordFieldKind::profile, false, "", {}, 1},
            {RecordFieldId{6}, "name_space", RecordFieldKind::text, false, "", {}, 1},
            {RecordFieldId{7}, "number", RecordFieldKind::unsigned_integer, false, "", {}, 1},
        };
        result.encode = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            RecordInput input{{type_id, value.id.value}, 1, {}};
            input.fields.push_back({RecordFieldId{2},
                                    RecordFieldKind::reference,
                                    "",
                                    record_wire::text((value.entity).value)});
            input.fields.push_back({RecordFieldId{3},
                                    RecordFieldKind::text,
                                    "",
                                    record_wire::text(value.source_model_id)});
            input.fields.push_back({RecordFieldId{4},
                                    RecordFieldKind::reference,
                                    "",
                                    record_wire::text((value.include).value)});
            input.fields.push_back({RecordFieldId{5},
                                    RecordFieldKind::profile,
                                    "",
                                    record_wire::profile(value.profile)});
            input.fields.push_back(
                {RecordFieldId{6}, RecordFieldKind::text, "", record_wire::text(value.name_space)});
            input.fields.push_back({RecordFieldId{7},
                                    RecordFieldKind::unsigned_integer,
                                    "",
                                    record_wire::number(value.number)});
            return input;
        };
        result.decode = [](const RecordInput& input) -> std::shared_ptr<const void> {
            Value value;
            value.id = decltype(value.id)(input.key.identity);
            value.entity = EntityId(
                record_wire::read_text(record_wire::require(input, RecordFieldId{2}).payload));
            value.source_model_id =
                record_wire::read_text(record_wire::require(input, RecordFieldId{3}).payload);
            value.include = EntityId(
                record_wire::read_text(record_wire::require(input, RecordFieldId{4}).payload));
            value.profile =
                record_wire::read_profile(record_wire::require(input, RecordFieldId{5}).payload);
            value.name_space =
                record_wire::read_text(record_wire::require(input, RecordFieldId{6}).payload);
            value.number =
                record_wire::read_number(record_wire::require(input, RecordFieldId{7}).payload);
            validate_fields(value);
            return std::make_shared<const Value>(std::move(value));
        };
        result.owned_bytes = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            return sizeof(Value) + records_detail::dynamic_bytes(value.id) +
                   records_detail::dynamic_bytes(value.entity) +
                   records_detail::dynamic_bytes(value.source_model_id) +
                   records_detail::dynamic_bytes(value.include) +
                   records_detail::dynamic_bytes(value.profile) +
                   records_detail::dynamic_bytes(value.name_space) +
                   records_detail::dynamic_bytes(value.number);
        };
        result.references = [](const void* object, const RecordReferenceVisitor& visitor) {
            const auto& value = *static_cast<const Value*>(object);
            static constexpr std::array targets_2{RecordTypeId{4097},
                                                  RecordTypeId{4098},
                                                  RecordTypeId{4099},
                                                  RecordTypeId{4100},
                                                  RecordTypeId{4101},
                                                  RecordTypeId{4102},
                                                  RecordTypeId{4103},
                                                  RecordTypeId{4105},
                                                  RecordTypeId{4106},
                                                  RecordTypeId{4107},
                                                  RecordTypeId{4111}};
            visitor(RecordFieldId{2}, value.entity.value, targets_2);
            static constexpr std::array targets_4{RecordTypeId{4104}};
            visitor(RecordFieldId{4}, value.include.value, targets_4);
        };
        result.validate = [](const void* object, const DocumentView& view) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            (void)view;
        };
        return result;
    }
};
template <> struct RecordTraits<records::GeometryLine> {
    using Value = records::GeometryLine;
    static constexpr RecordTypeId type_id{4109};
    inline static const unsigned char token_value{};
    static const void* token() noexcept {
        return &token_value;
    }
    static const std::string& identity(const Value& value) noexcept {
        return value.id.value;
    }
    static void validate_fields(const Value& value) {
        records_detail::check_text(value.id.value, true, "id");
        for (double part : value.start)
            if (!std::isfinite(part))
                records_detail::invalid("Vector must be finite", "start");
        for (double part : value.end)
            if (!std::isfinite(part))
                records_detail::invalid("Vector must be finite", "end");
        if (value.geometry_revision < 1)
            records_detail::invalid("Field is outside its allowed range", "geometry_revision");
    }
    static RecordDescriptor descriptor() {
        RecordDescriptor result;
        result.type = type_id;
        result.name = "GeometryLine";
        result.query_kind = "geometry";
        result.display_name = [](const void*) -> std::string_view { return {}; };
        result.current_version = 1;
        result.cpp_type_token = token();
        result.maximum_encoded_bytes = 16777216;
        result.fields = {
            {RecordFieldId{2}, "start", RecordFieldKind::vector3, false, "mm", {}, 1},
            {RecordFieldId{3}, "end", RecordFieldKind::vector3, false, "mm", {}, 1},
            {RecordFieldId{4},
             "geometry_revision",
             RecordFieldKind::unsigned_integer,
             false,
             "",
             {},
             1},
        };
        result.encode = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            RecordInput input{{type_id, value.id.value}, 1, {}};
            input.fields.push_back({RecordFieldId{2},
                                    RecordFieldKind::vector3,
                                    "mm",
                                    record_wire::vector3(value.start)});
            input.fields.push_back({RecordFieldId{3},
                                    RecordFieldKind::vector3,
                                    "mm",
                                    record_wire::vector3(value.end)});
            input.fields.push_back({RecordFieldId{4},
                                    RecordFieldKind::unsigned_integer,
                                    "",
                                    record_wire::number(value.geometry_revision)});
            return input;
        };
        result.decode = [](const RecordInput& input) -> std::shared_ptr<const void> {
            Value value;
            value.id = decltype(value.id)(input.key.identity);
            value.start =
                record_wire::read_vector3(record_wire::require(input, RecordFieldId{2}).payload);
            value.end =
                record_wire::read_vector3(record_wire::require(input, RecordFieldId{3}).payload);
            value.geometry_revision =
                record_wire::read_number(record_wire::require(input, RecordFieldId{4}).payload);
            validate_fields(value);
            return std::make_shared<const Value>(std::move(value));
        };
        result.owned_bytes = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            return sizeof(Value) + records_detail::dynamic_bytes(value.id) +
                   records_detail::dynamic_bytes(value.start) +
                   records_detail::dynamic_bytes(value.end) +
                   records_detail::dynamic_bytes(value.geometry_revision);
        };
        result.references = [](const void* object, const RecordReferenceVisitor& visitor) {
            (void)object;
            (void)visitor;
        };
        result.validate = [](const void* object, const DocumentView& view) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            records::validate_record(value, view);
        };
        return result;
    }
};
template <> struct RecordTraits<records::Mesh> {
    using Value = records::Mesh;
    static constexpr RecordTypeId type_id{4110};
    inline static const unsigned char token_value{};
    static const void* token() noexcept {
        return &token_value;
    }
    static const std::string& identity(const Value& value) noexcept {
        return value.id.value;
    }
    static void validate_fields(const Value& value) {
        records_detail::check_text(value.id.value, true, "id");
        records_detail::check_text(value.name, false, "name");
        records_detail::check_text(value.origin, false, "origin");
        if (value.origin != "imported" && value.origin != "manual" && value.origin != "geometry")
            records_detail::invalid("Unknown field value", "origin");
        if (value.geometry) {
            records_detail::check_text((*value.geometry).value, true, "geometry");
        }
    }
    static RecordDescriptor descriptor() {
        RecordDescriptor result;
        result.type = type_id;
        result.name = "Mesh";
        result.query_kind = "mesh";
        result.display_name = [](const void* object) -> std::string_view {
            return static_cast<const Value*>(object)->name;
        };
        result.current_version = 1;
        result.cpp_type_token = token();
        result.maximum_encoded_bytes = 16777216;
        result.fields = {
            {RecordFieldId{2}, "name", RecordFieldKind::text, false, "", {}, 1},
            {RecordFieldId{3}, "origin", RecordFieldKind::text, false, "", {}, 1},
            {RecordFieldId{4},
             "geometry",
             RecordFieldKind::reference,
             true,
             "",
             {RecordTypeId{4109}},
             1},
            {RecordFieldId{5},
             "geometry_revision",
             RecordFieldKind::unsigned_integer,
             false,
             "",
             {},
             1},
            {RecordFieldId{6}, "stale", RecordFieldKind::boolean, false, "", {}, 1},
        };
        result.encode = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            RecordInput input{{type_id, value.id.value}, 1, {}};
            input.fields.push_back(
                {RecordFieldId{2}, RecordFieldKind::text, "", record_wire::text(value.name)});
            input.fields.push_back(
                {RecordFieldId{3}, RecordFieldKind::text, "", record_wire::text(value.origin)});
            if (value.geometry) {
                input.fields.push_back({RecordFieldId{4},
                                        RecordFieldKind::reference,
                                        "",
                                        record_wire::text((*value.geometry).value)});
            }
            input.fields.push_back({RecordFieldId{5},
                                    RecordFieldKind::unsigned_integer,
                                    "",
                                    record_wire::number(value.geometry_revision)});
            input.fields.push_back({RecordFieldId{6},
                                    RecordFieldKind::boolean,
                                    "",
                                    record_wire::boolean(value.stale)});
            return input;
        };
        result.decode = [](const RecordInput& input) -> std::shared_ptr<const void> {
            Value value;
            value.id = decltype(value.id)(input.key.identity);
            value.name =
                record_wire::read_text(record_wire::require(input, RecordFieldId{2}).payload);
            value.origin =
                record_wire::read_text(record_wire::require(input, RecordFieldId{3}).payload);
            if (const auto* field = record_wire::find(input, RecordFieldId{4})) {
                value.geometry = records::GeometryId(record_wire::read_text(field->payload));
            }
            value.geometry_revision =
                record_wire::read_number(record_wire::require(input, RecordFieldId{5}).payload);
            value.stale =
                record_wire::read_boolean(record_wire::require(input, RecordFieldId{6}).payload);
            validate_fields(value);
            return std::make_shared<const Value>(std::move(value));
        };
        result.owned_bytes = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            return sizeof(Value) + records_detail::dynamic_bytes(value.id) +
                   records_detail::dynamic_bytes(value.name) +
                   records_detail::dynamic_bytes(value.origin) +
                   records_detail::dynamic_bytes(value.geometry) +
                   records_detail::dynamic_bytes(value.geometry_revision) +
                   records_detail::dynamic_bytes(value.stale);
        };
        result.references = [](const void* object, const RecordReferenceVisitor& visitor) {
            const auto& value = *static_cast<const Value*>(object);
            static constexpr std::array targets_4{RecordTypeId{4109}};
            if (value.geometry)
                visitor(RecordFieldId{4}, value.geometry->value, targets_4);
        };
        result.validate = [](const void* object, const DocumentView& view) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            records::validate_record(value, view);
        };
        return result;
    }
};
template <> struct RecordTraits<records::LoadCase> {
    using Value = records::LoadCase;
    static constexpr RecordTypeId type_id{4111};
    inline static const unsigned char token_value{};
    static const void* token() noexcept {
        return &token_value;
    }
    static const std::string& identity(const Value& value) noexcept {
        return value.id.value;
    }
    static void validate_fields(const Value& value) {
        records_detail::check_text(value.id.value, true, "id");
        records_detail::check_text(value.name, true, "name");
        records_detail::check_references(value.forces, "forces");
        records_detail::check_references(value.constraints, "constraints");
    }
    static RecordDescriptor descriptor() {
        RecordDescriptor result;
        result.type = type_id;
        result.name = "LoadCase";
        result.query_kind = "load_case";
        result.display_name = [](const void* object) -> std::string_view {
            return static_cast<const Value*>(object)->name;
        };
        result.current_version = 1;
        result.cpp_type_token = token();
        result.maximum_encoded_bytes = 16777216;
        result.fields = {
            {RecordFieldId{2}, "name", RecordFieldKind::text, false, "", {}, 1},
            {RecordFieldId{3},
             "forces",
             RecordFieldKind::references,
             false,
             "",
             {RecordTypeId{4105}},
             1},
            {RecordFieldId{4},
             "constraints",
             RecordFieldKind::references,
             false,
             "",
             {RecordTypeId{4106}},
             1},
        };
        result.encode = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            RecordInput input{{type_id, value.id.value}, 1, {}};
            input.fields.push_back(
                {RecordFieldId{2}, RecordFieldKind::text, "", record_wire::text(value.name)});
            input.fields.push_back({RecordFieldId{3},
                                    RecordFieldKind::references,
                                    "",
                                    records_detail::pack_references(value.forces)});
            input.fields.push_back({RecordFieldId{4},
                                    RecordFieldKind::references,
                                    "",
                                    records_detail::pack_references(value.constraints)});
            return input;
        };
        result.decode = [](const RecordInput& input) -> std::shared_ptr<const void> {
            Value value;
            value.id = decltype(value.id)(input.key.identity);
            value.name =
                record_wire::read_text(record_wire::require(input, RecordFieldId{2}).payload);
            value.forces = records_detail::unpack_references<std::vector<EntityId>>(
                record_wire::require(input, RecordFieldId{3}).payload);
            value.constraints = records_detail::unpack_references<std::vector<EntityId>>(
                record_wire::require(input, RecordFieldId{4}).payload);
            validate_fields(value);
            return std::make_shared<const Value>(std::move(value));
        };
        result.owned_bytes = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            return sizeof(Value) + records_detail::dynamic_bytes(value.id) +
                   records_detail::dynamic_bytes(value.name) +
                   records_detail::dynamic_bytes(value.forces) +
                   records_detail::dynamic_bytes(value.constraints);
        };
        result.references = [](const void* object, const RecordReferenceVisitor& visitor) {
            const auto& value = *static_cast<const Value*>(object);
            static constexpr std::array targets_3{RecordTypeId{4105}};
            for (const auto& item : value.forces)
                visitor(RecordFieldId{3}, item.value, targets_3);
            static constexpr std::array targets_4{RecordTypeId{4106}};
            for (const auto& item : value.constraints)
                visitor(RecordFieldId{4}, item.value, targets_4);
        };
        result.validate = [](const void* object, const DocumentView& view) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            (void)view;
        };
        return result;
    }
};
template <> struct RecordTraits<records::Tri3> {
    using Value = records::Tri3;
    static constexpr RecordTypeId type_id{4112};
    inline static const unsigned char token_value{};
    static const void* token() noexcept {
        return &token_value;
    }
    static const std::string& identity(const Value& value) noexcept {
        return value.id.value;
    }
    static void validate_fields(const Value& value) {
        records_detail::check_text(value.id.value, true, "id");
        records_detail::check_references(value.nodes, "nodes");
        records_detail::check_text((value.mesh).value, true, "mesh");
    }
    static RecordDescriptor descriptor() {
        RecordDescriptor result;
        result.type = type_id;
        result.name = "Tri3";
        result.query_kind = "tri3";
        result.display_name = [](const void*) -> std::string_view { return {}; };
        result.current_version = 1;
        result.cpp_type_token = token();
        result.maximum_encoded_bytes = 4096;
        result.fields = {
            {RecordFieldId{2},
             "nodes",
             RecordFieldKind::references,
             false,
             "",
             {RecordTypeId{4098}},
             1},
            {RecordFieldId{3},
             "mesh",
             RecordFieldKind::reference,
             false,
             "",
             {RecordTypeId{4110}},
             1},
        };
        result.encode = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            RecordInput input{{type_id, value.id.value}, 1, {}};
            input.fields.push_back({RecordFieldId{2},
                                    RecordFieldKind::references,
                                    "",
                                    records_detail::pack_references(value.nodes)});
            input.fields.push_back({RecordFieldId{3},
                                    RecordFieldKind::reference,
                                    "",
                                    record_wire::text((value.mesh).value)});
            return input;
        };
        result.decode = [](const RecordInput& input) -> std::shared_ptr<const void> {
            Value value;
            value.id = decltype(value.id)(input.key.identity);
            value.nodes = records_detail::unpack_references<std::array<EntityId, 3>>(
                record_wire::require(input, RecordFieldId{2}).payload);
            value.mesh = records::MeshId(
                record_wire::read_text(record_wire::require(input, RecordFieldId{3}).payload));
            validate_fields(value);
            return std::make_shared<const Value>(std::move(value));
        };
        result.owned_bytes = [](const void* object) {
            const auto& value = *static_cast<const Value*>(object);
            return sizeof(Value) + records_detail::dynamic_bytes(value.id) +
                   records_detail::dynamic_bytes(value.nodes) +
                   records_detail::dynamic_bytes(value.mesh);
        };
        result.references = [](const void* object, const RecordReferenceVisitor& visitor) {
            const auto& value = *static_cast<const Value*>(object);
            static constexpr std::array targets_2{RecordTypeId{4098}};
            for (const auto& item : value.nodes)
                visitor(RecordFieldId{2}, item.value, targets_2);
            static constexpr std::array targets_3{RecordTypeId{4110}};
            visitor(RecordFieldId{3}, value.mesh.value, targets_3);
        };
        result.validate = [](const void* object, const DocumentView& view) {
            const auto& value = *static_cast<const Value*>(object);
            validate_fields(value);
            records::validate_record(value, view);
        };
        return result;
    }
};
inline std::vector<RecordDescriptor> generated_record_descriptors() {
    return {
        RecordTraits<records::Material>::descriptor(),
        RecordTraits<records::Node>::descriptor(),
        RecordTraits<records::BeamSection>::descriptor(),
        RecordTraits<records::Beam>::descriptor(),
        RecordTraits<records::Part>::descriptor(),
        RecordTraits<records::Assembly>::descriptor(),
        RecordTraits<records::EntitySet>::descriptor(),
        RecordTraits<records::IncludeDocument>::descriptor(),
        RecordTraits<records::NodalForce>::descriptor(),
        RecordTraits<records::Constraint>::descriptor(),
        RecordTraits<records::AnalysisDefinition>::descriptor(),
        RecordTraits<records::SourceIdentifier>::descriptor(),
        RecordTraits<records::GeometryLine>::descriptor(),
        RecordTraits<records::Mesh>::descriptor(),
        RecordTraits<records::LoadCase>::descriptor(),
        RecordTraits<records::Tri3>::descriptor(),
    };
}
std::shared_ptr<const RecordRegistry> make_record_registry();
} // namespace qcae
