add_library(qcae_material_features STATIC src/material_operations.cpp include/qcae/material_operations.hpp)
target_include_directories(qcae_material_features PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}/include")
target_compile_features(qcae_material_features PUBLIC cxx_std_20)
target_link_libraries(qcae_material_features PUBLIC qcae_application qcae_operations qcae_parameters)
qcae_warnings(qcae_material_features)
